// SPDX-License-Identifier: AGPL-3.0-only

//! Cross-validation against an independent open implementation.
//!
//! Per forcing function §3.4 + spec §1.Q6. Compares statistical
//! properties (mean power, autocorrelation function, per-bin spectral
//! magnitude) between hf-channel-sim and a reference output captured
//! from GNU Radio's `fading_model` block at the same WattersonParams.
//!
//! Bit-identity is NOT expected (different RNGs, different shaping
//! filters); statistical agreement IS.
//!
//! Reference fixtures are generated by a separate Python script
//! (see docs/cross-validation.md) and committed as binary f32
//! files in tests/fixtures/.

use hf_channel_sim::{ChannelCondition, WattersonChannel};
use num_complex::Complex;
use std::fs;
use std::path::PathBuf;

fn load_fixture(name: &str) -> Option<Vec<Complex<f32>>> {
    let path: PathBuf = ["tests", "fixtures", name].iter().collect();
    let bytes = fs::read(&path).ok()?;
    if bytes.len() % 8 != 0 {
        return None;
    }
    let mut out = Vec::with_capacity(bytes.len() / 8);
    let mut i = 0;
    while i + 8 <= bytes.len() {
        let re = f32::from_le_bytes([bytes[i], bytes[i + 1], bytes[i + 2], bytes[i + 3]]);
        let im = f32::from_le_bytes([bytes[i + 4], bytes[i + 5], bytes[i + 6], bytes[i + 7]]);
        out.push(Complex { re, im });
        i += 8;
    }
    Some(out)
}

fn mean_power(v: &[Complex<f32>]) -> f64 {
    v.iter().map(|c| c.norm_sqr() as f64).sum::<f64>() / v.len() as f64
}

#[test]
#[ignore = "requires GNU Radio fixture; see docs/cross-validation.md"]
fn power_matches_gnuradio_reference_moderate_condition() {
    let reference = load_fixture("gr_moderate_unit_input_seed1.f32")
        .expect("fixture missing — run scripts/generate_gr_fixtures.py first");
    // The Python script applies fading_model to a constant unit-real input of
    // length matching `reference.len()`. We do the same and compare mean power.
    let input: Vec<Complex<f32>> = vec![Complex { re: 1.0, im: 0.0 }; reference.len()];
    let mut ch = WattersonChannel::from_condition(1, ChannelCondition::Moderate, 8000.0);
    let our_out = ch.process_block(&input);

    let p_ref = mean_power(&reference);
    let p_ours = mean_power(&our_out);
    // Expect mean power within 0.5 dB.
    let ratio_db = 10.0 * (p_ours / p_ref).log10();
    assert!(
        ratio_db.abs() < 0.5,
        "mean power differs by {ratio_db} dB; ref={p_ref}, ours={p_ours}",
    );
}
