//! rmcp tool router for the Tuxlink MCP server (phase 3.1).
//!
//! [`TuxlinkMcp`] is the rmcp handler. It owns the shared [`McpState`] and a
//! generated [`ToolRouter`]. Phase 3.1 registers exactly one tool —
//! [`TuxlinkMcp::server_info`] — a thin wrapper over the pure
//! [`server_info_view`](crate::mcp::server_info_view); all logic lives there so
//! the transport layer stays untested-by-design (it is exercised at tier-2).

use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::ServerHandler;
use rmcp::model::{
    CallToolResult, Content, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo,
};
use rmcp::{tool, tool_handler, tool_router, ErrorData};

use crate::mcp::{server_info_view, McpState};

/// The Tuxlink MCP server handler. Cloned per the rmcp serve loop; the inner
/// [`McpState`] is `Arc`-shared so all clones see the same live guard state.
#[derive(Clone)]
pub struct TuxlinkMcp {
    state: Arc<McpState>,
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl TuxlinkMcp {
    /// Build the handler around a shared [`McpState`]. `Self::tool_router()` is
    /// generated by the `#[tool_router]` macro from the `#[tool]` methods below.
    pub fn new(state: Arc<McpState>) -> Self {
        Self {
            state,
            tool_router: Self::tool_router(),
        }
    }

    /// Report the app identity and the live egress-authority state. Inert: it
    /// reads state only, never arms, taints, or egresses. The serializable shape
    /// is built by the pure [`server_info_view`]; this wrapper only encodes it
    /// into an rmcp tool result.
    #[tool(
        name = "server_info",
        description = "Report the Tuxlink app name/version and the live egress-authority state (armed, tainted). Read-only; does not transmit or change any state."
    )]
    pub async fn server_info(&self) -> Result<CallToolResult, ErrorData> {
        let dto = server_info_view(&self.state);
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }
}

#[tool_handler]
impl ServerHandler for TuxlinkMcp {
    fn get_info(&self) -> ServerInfo {
        // `ServerInfo` (= `InitializeResult`) is `#[non_exhaustive]`, so it
        // cannot be built with a struct literal NOR `..Default::default()` from
        // this crate; mutating fields after `default()` is the only path. The
        // clippy lint that flags reassign-after-default does not apply here
        // because the literal form is unavailable for a non-exhaustive struct.
        #[allow(clippy::field_reassign_with_default)]
        let mut info = ServerInfo::default();
        info.protocol_version = ProtocolVersion::LATEST;
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info.server_info = Implementation::from_build_env();
        info.instructions = Some(
            "Tuxlink MCP server. `server_info` reports the app version and the \
             operator's live send-authority state (armed, tainted)."
                .to_string(),
        );
        info
    }
}
