//! Enriched-catalog JSONL parsing and the embed-text template.
//!
//! The asset (`src-tauri/resources/catalog/winlink-catalog-enriched.jsonl`)
//! is generated by `scripts/enrich_catalog.py` from the upstream catalog;
//! the generator hard-fails on uncurated sections and `--check` verifies the
//! committed asset byte-for-byte. The parity test in this module is the CI
//! side of that drift gate.

use serde::{Deserialize, Serialize};

use crate::ClassifyError;

/// T0 structured facts parsed at index time (ADR 0030: geo/numerics belong
/// to deterministic parsing, not embeddings — the T1 spike's coordinates
/// probe failed semantically and this is the designed answer). Never
/// embedded; consumed by deterministic callers (locality filtering/ranking).
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct GeoFacts {
    /// Two-letter US state/territory code when the item is state-scoped.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lat: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub lon: Option<f64>,
}

/// One enriched corpus item — the JSONL object shape the 2026-08-10
/// parseability spike validated against the served backend (42/44 select,
/// 6/6 structural parse, zero hallucinated ids).
///
/// Tolerant reader by design (no `deny_unknown_fields`): corpus assets are
/// shared artifacts — the tool-surface corpus carries extra flag fields
/// (`taints`, `arm_required`) for its inventory/docs consumers, and this
/// crate embeds only the fields it knows.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnrichedEntry {
    pub id: String,
    pub section: String,
    pub title: String,
    pub intent: String,
    pub synonyms: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub geo: Option<GeoFacts>,
}

/// Version tag of [`embed_text`]'s template. Thresholds are calibrated per
/// (corpus, model, template) — ANY change to the template string below must
/// bump this and recalibrate (ADR 0030's "threshold rot" watched failure
/// mode). The tag is part of the [`crate::ThresholdKey`].
pub const EMBED_TEMPLATE_VERSION: &str = "enriched-v1";

/// The text a catalog item is embedded as.
///
/// Extends the T1 spike's winning `SECTION ID: description` shape (+8–17
/// top-1 points over description-only) with the enrichment fields. `geo` is
/// deliberately absent — coordinates are T0 data, and embedding them is the
/// failure mode the spike documented.
pub fn embed_text(e: &EnrichedEntry) -> String {
    let syn = e.synonyms.join(", ");
    format!(
        "{} {}: {}. {}. Also known as: {}",
        e.section, e.id, e.title, e.intent, syn
    )
}

/// Parse the enriched-index JSONL (one object per line, blank lines
/// tolerated). Duplicate ids are an error: the id is the item_ref the whole
/// advisory chain hands around.
pub fn parse_jsonl(text: &str) -> Result<Vec<EnrichedEntry>, ClassifyError> {
    let mut out: Vec<EnrichedEntry> = Vec::new();
    let mut seen = std::collections::BTreeSet::new();
    for (n, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let e: EnrichedEntry = serde_json::from_str(line)
            .map_err(|err| ClassifyError::Parse(format!("line {}: {err}", n + 1)))?;
        if !seen.insert(e.id.clone()) {
            return Err(ClassifyError::Parse(format!("duplicate id {}", e.id)));
        }
        out.push(e);
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed enriched asset and the upstream catalog it derives from.
    const ENRICHED: &str =
        include_str!("../../resources/catalog/winlink-catalog-enriched.jsonl");
    const CATALOG: &str = include_str!("../../resources/catalog/winlink-queries.txt");

    fn catalog_ids() -> std::collections::BTreeSet<String> {
        CATALOG
            .trim_start_matches('\u{feff}')
            .lines()
            .filter_map(|l| {
                let mut parts = l.trim().split('|');
                let _section = parts.next()?;
                parts.next().map(|id| id.trim().to_string())
            })
            .filter(|id| !id.is_empty())
            .collect()
    }

    /// CI half of the enrichment drift gate: every upstream catalog item is
    /// enriched exactly once, and nothing enriched is missing upstream. A
    /// catalog update without `scripts/enrich_catalog.py` regeneration (and
    /// the threshold recalibration that follows) fails here.
    #[test]
    fn enriched_asset_covers_catalog_exactly() {
        let entries = parse_jsonl(ENRICHED).expect("committed asset parses");
        let enriched_ids: std::collections::BTreeSet<String> =
            entries.iter().map(|e| e.id.clone()).collect();
        let upstream = catalog_ids();
        assert_eq!(entries.len(), upstream.len(), "entry count == catalog rows");
        let missing: Vec<_> = upstream.difference(&enriched_ids).collect();
        let stale: Vec<_> = enriched_ids.difference(&upstream).collect();
        assert!(missing.is_empty(), "catalog ids missing enrichment: {missing:?}");
        assert!(stale.is_empty(), "enriched ids not in catalog: {stale:?}");
    }

    /// Every entry carries non-empty retrieval text — an empty intent or
    /// synonym list means the generator's curation regressed.
    #[test]
    fn enriched_entries_are_nonempty() {
        for e in parse_jsonl(ENRICHED).unwrap() {
            assert!(!e.intent.trim().is_empty(), "{}: empty intent", e.id);
            assert!(!e.synonyms.is_empty(), "{}: no synonyms", e.id);
            assert!(!e.title.trim().is_empty(), "{}: empty title", e.id);
        }
    }

    /// Template snapshot: a change here is a calibration-invalidating event
    /// and must bump EMBED_TEMPLATE_VERSION (the assert message says so).
    #[test]
    fn embed_template_snapshot() {
        let e = EnrichedEntry {
            id: "AUR_TONIGHT".into(),
            section: "AURORA".into(),
            title: "NOAA Aurora Viewline for Tonight".into(),
            intent: "NOAA aurora visibility (viewline) forecasts".into(),
            synonyms: vec!["aurora".into(), "northern lights".into()],
            geo: None,
        };
        assert_eq!(
            embed_text(&e),
            "AURORA AUR_TONIGHT: NOAA Aurora Viewline for Tonight. NOAA aurora \
             visibility (viewline) forecasts. Also known as: aurora, northern lights",
            "embed template changed: bump EMBED_TEMPLATE_VERSION ({EMBED_TEMPLATE_VERSION}) \
             and recalibrate thresholds per ADR 0030"
        );
    }

    /// The buoy-coordinates class the T1 spike flagged: geo facts must
    /// survive the asset round-trip (NDBC46026 is the San Francisco buoy
    /// behind the spike's one semantic failure).
    #[test]
    fn geo_facts_present_for_sf_buoy() {
        let entries = parse_jsonl(ENRICHED).unwrap();
        let sf = entries.iter().find(|e| e.id == "NDBC46026").expect("NDBC46026");
        let geo = sf.geo.as_ref().expect("geo parsed");
        let (lat, lon) = (geo.lat.unwrap(), geo.lon.unwrap());
        assert!((lat - 37.75).abs() < 0.01 && (lon + 122.84).abs() < 0.01);
    }
}
