/**
 * elmerEvents — TypeScript mirror of src-tauri/src/elmer/events.rs.
 *
 * Event-name constants and payload interfaces MUST match the Rust serde contract
 * exactly. The Rust enum uses `#[serde(tag = "kind", rename_all = "camelCase")]`,
 * so the discriminant is `event.payload.kind`. The `Outcome` variant emits
 * `outcomeKind` (not `kind`) for the outcome's category to avoid a name collision
 * with the tag field — confirmed in events.rs line 59.
 *
 * DO NOT rename these constants or interface fields without updating events.rs.
 */

// ---------------------------------------------------------------------------
// Event-name constants (Rust ↔ TypeScript contract)
// ---------------------------------------------------------------------------

/** Streaming text token from the model (role + text snippet). */
export const EV_TURN = 'elmer-turn' as const;

/** A tool was called or returned (tool name + status string). */
export const EV_CHIP = 'elmer-chip' as const;

/** The run reached a terminal outcome (outcomeKind string + optional detail). */
export const EV_OUTCOME = 'elmer-outcome' as const;

/**
 * An incremental streamed text chunk during a turn (assistant answer or
 * reasoning). Emitted zero-or-more times BEFORE the final EV_TURN.
 *
 * Streaming providers emit a sequence per turn: zero or more EV_DELTA (reasoning
 * and/or assistant chunks, reasoning-then-answer ordered) → then EV_TURN (the
 * FULL final answer) → then EV_OUTCOME. Non-streaming providers emit NO
 * EV_DELTA — just EV_TURN — so any consumer MUST treat EV_DELTA as optional.
 */
export const EV_DELTA = 'elmer-delta' as const;

/**
 * Context-usage snapshot emitted by OllamaProvider after each turn (T7).
 * Carries the prompt token count, eval (completion) token count, and the
 * configured context window size so the frontend can render a fill meter.
 * Emitted at most once per completed turn; never emitted by cloud providers.
 */
export const EV_CONTEXT = 'elmer-context' as const;

// ---------------------------------------------------------------------------
// Payload interfaces (mirror ElmerEvent Rust enum variants, camelCase)
// ---------------------------------------------------------------------------

/**
 * A text token (or full assistant/user/system turn) from the model.
 * Emitted on EV_TURN.
 */
export interface ElmerTurnPayload {
  kind: 'turn';
  /** 'user' | 'assistant' | 'system' */
  role: string;
  /** The text content of the turn. */
  text: string;
}

/**
 * A tool was invoked or returned.
 * Emitted on EV_CHIP.
 */
export interface ElmerChipPayload {
  kind: 'chip';
  /** MCP tool name, e.g. 'find_stations'. */
  tool: string;
  /** Human-readable status, e.g. 'calling' | 'ok' | 'denied'. */
  status: string;
}

/**
 * The run loop exited with a terminal outcome.
 * Emitted on EV_OUTCOME.
 *
 * IMPORTANT: the category field is `outcomeKind`, NOT `kind` — the Rust
 * serde tag uses `"kind"` as the discriminant for the enum variant ("outcome"),
 * and `outcome_kind` (→ camelCase `outcomeKind`) carries the terminal state.
 *
 * Possible outcomeKind values: 'done' | 'cancelled' | 'needsOperator' |
 * 'toolDenied' | 'offline' | 'error' (the Rust side may emit others; treat
 * any unknown value as a generic error state in the UI).
 */
export interface ElmerOutcomePayload {
  kind: 'outcome';
  /** Terminal state category. */
  outcomeKind: string;
  /** Operator-facing detail string (already redacted at the session layer). */
  detail: string;
}

/**
 * An incremental streamed chunk of text during a turn.
 * Emitted on EV_DELTA.
 *
 * IMPORTANT: the discriminant category is `deltaKind`, NOT `kind` — the Rust
 * serde tag uses `"kind"` as the enum-variant discriminant (always the literal
 * `"delta"` here), and `delta_kind` (→ camelCase `deltaKind`) carries whether
 * this chunk is part of the model's reasoning trace or its assistant answer.
 * Read `payload.deltaKind` to route the chunk; `payload.kind` is the serde tag.
 */
export interface ElmerDeltaPayload {
  kind: 'delta';
  /** 'assistant' — answer text; 'reasoning' — the model's thinking trace. */
  deltaKind: 'assistant' | 'reasoning';
  /** The incremental text fragment to append to the matching buffer. */
  chunk: string;
}

/**
 * Context-usage snapshot from a completed Ollama turn (T7 / EV_CONTEXT).
 * Emitted on EV_CONTEXT after the final `/api/chat` response is parsed.
 *
 * Fields mirror the Rust serde contract (camelCase, tag="kind"):
 *   promptTokens  — tokens consumed by the prompt (Ollama: `prompt_eval_count`).
 *   evalTokens    — tokens generated in the completion (`eval_count`).
 *   numCtx        — context window (Ollama num_ctx / compat probe); null when unknown → counter-mode.
 */
export interface ElmerContextPayload {
  kind: 'context';
  /** Tokens consumed by the prompt (`prompt_eval_count` in the Ollama response). */
  promptTokens: number;
  /** Tokens generated by the model (`eval_count` in the Ollama response). */
  evalTokens: number;
  /** Context window (Ollama num_ctx / compat probe); null when unknown → counter-mode. */
  numCtx: number | null;
}

/** Union of all Elmer event payloads. Switch on `payload.kind`. */
export type ElmerPayload =
  | ElmerTurnPayload
  | ElmerChipPayload
  | ElmerOutcomePayload
  | ElmerDeltaPayload
  | ElmerContextPayload;
