//! T2.3 — thin end-to-end known-answer test for the M2 real-WAV acquisition
//! slice. Reads each committed `gen_ft8`-generated fixture WAV, runs the full
//! pipeline (channelize → Costas sync + rank + refine + extract → soft-demap →
//! LDPC decode → guard → unpack), and asserts the decoded string equals the
//! fixture's known transmitted message. Also asserts ZERO false decodes on
//! silence and pure noise.
//!
//! This is the M2 HARD-STOP gate: all five fixtures must decode to their exact
//! known message with no false decodes.
//!
//! Clean-room: the fixtures are generated by the independent MIT `ft8_lib`
//! encoder (see `tests/fixtures/gen/README.md`), so this is a genuine
//! cross-implementation check of the decoder, not a self-consistency round-trip.

use std::path::PathBuf;
use tuxlink_ft8::sync::decode_samples;

/// Load a committed gen fixture WAV as f32 samples, asserting its format.
fn load_fixture(name: &str) -> Vec<f32> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/fixtures/gen");
    path.push(name);
    let mut reader =
        hound::WavReader::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    let spec = reader.spec();
    assert_eq!(spec.sample_rate, 12_000, "{name}: fixture must be 12 kHz");
    assert_eq!(spec.channels, 1, "{name}: fixture must be mono");
    assert_eq!(spec.bits_per_sample, 16, "{name}: fixture must be 16-bit");
    reader
        .samples::<i16>()
        .map(|s| s.expect("read sample") as f32)
        .collect()
}

/// Every fixture decodes to its exact known message (three messages × three
/// carriers). The known-answer manifest is `tests/fixtures/gen/README.md`.
#[test]
fn all_five_fixtures_decode_to_known_message() {
    let cases = [
        ("std_cq_1500.wav", "CQ K1ABC FN42"),
        ("freetext_1500.wav", "TNX BOB 73 GL"),
        ("nonstd_cq_1500.wav", "CQ PJ4/K1ABC"),
        ("std_cq_0800.wav", "CQ K1ABC FN42"),
        ("std_cq_2400.wav", "CQ K1ABC FN42"),
    ];

    for (file, expected) in cases {
        let samples = load_fixture(file);
        let decodes = decode_samples(&samples, 12_000);
        assert!(
            decodes.iter().any(|d| d.message == expected),
            "{file}: expected to decode {expected:?}, got {:?}",
            decodes.iter().map(|d| &d.message).collect::<Vec<_>>()
        );
    }
}

/// The winning decode's sync metric clears the guard floor and its carrier is at
/// the right place — a spot check that the pipeline reports coherent metadata,
/// not just the right string.
#[test]
fn winning_candidate_metadata_is_coherent() {
    let samples = load_fixture("std_cq_1500.wav");
    let decodes = decode_samples(&samples, 12_000);
    let d = decodes
        .iter()
        .find(|d| d.message == "CQ K1ABC FN42")
        .expect("std_cq_1500 must decode");
    assert!(
        d.sync_metric >= tuxlink_ft8::sync::SYNC_FLOOR,
        "winning sync metric {} below floor",
        d.sync_metric
    );
    assert!((d.freq_hz - 1500.0).abs() <= 1.0, "carrier {} not ≈1500", d.freq_hz);
    assert!(
        (d.start_sample - 14160.0).abs() <= 60.0,
        "start {} not near centred frame 14160",
        d.start_sample
    );
}

/// ZERO false decodes: a silent slot and a pure-noise slot both yield no decode
/// (no candidate clears the sync-metric floor / CRC / converged guard).
#[test]
fn silence_and_noise_yield_no_decode() {
    // Synthesized silent buffer.
    let silence = vec![0.0f32; 180_000];
    assert!(
        decode_samples(&silence, 12_000).is_empty(),
        "silent slot produced a false decode"
    );

    // The first ~1.0 s of a fixture is guaranteed silence (the centred frame does
    // not start until sample 14160 = 1.18 s); a whole-slot buffer of just that
    // silence must not decode.
    let head_silence = vec![0.0f32; 180_000];
    let real = load_fixture("std_cq_1500.wav");
    // Sanity: the fixture's leading 12000 samples (1.0 s) are silent.
    assert!(
        real[..12_000].iter().all(|&s| s == 0.0),
        "fixture lead-in is not silent as documented"
    );
    assert!(decode_samples(&head_silence, 12_000).is_empty());

    // Deterministic white noise (test-only LCG) — no Costas structure.
    let mut state = 0x9E37_79B9u32;
    let noise: Vec<f32> = (0..180_000)
        .map(|_| {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            (state >> 8) as f32 / (1u32 << 24) as f32 - 0.5
        })
        .collect();
    assert!(
        decode_samples(&noise, 12_000).is_empty(),
        "pure noise produced a false decode"
    );
}
