//! T2.3 — thin end-to-end known-answer test for the M2 real-WAV acquisition
//! slice. Reads each committed `gen_ft8`-generated fixture WAV, runs the full
//! pipeline (channelize → Costas sync + rank + refine + extract → soft-demap →
//! LDPC decode → guard → unpack), and asserts the decoded string equals the
//! fixture's known transmitted message. Also asserts ZERO false decodes on
//! silence and pure noise.
//!
//! This is the M2 HARD-STOP gate: all five fixtures must decode to their exact
//! known message with no false decodes.
//!
//! Clean-room: the fixtures are generated by the independent MIT `ft8_lib`
//! encoder (see `tests/fixtures/gen/README.md`), so this is a genuine
//! cross-implementation check of the decoder, not a self-consistency round-trip.

use std::path::PathBuf;
use tuxlink_ft8::sync::decode_samples;

/// Load a committed gen fixture WAV as f32 samples, asserting its format.
fn load_fixture(name: &str) -> Vec<f32> {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/fixtures/gen");
    path.push(name);
    let mut reader =
        hound::WavReader::open(&path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    let spec = reader.spec();
    assert_eq!(spec.sample_rate, 12_000, "{name}: fixture must be 12 kHz");
    assert_eq!(spec.channels, 1, "{name}: fixture must be mono");
    assert_eq!(spec.bits_per_sample, 16, "{name}: fixture must be 16-bit");
    reader
        .samples::<i16>()
        .map(|s| s.expect("read sample") as f32)
        .collect()
}

/// Every fixture decodes to its exact known message (three message types, four
/// carriers incl. one deliberately off the coarse grid). The known-answer
/// manifest is `tests/fixtures/gen/README.md`.
#[test]
fn all_fixtures_decode_to_known_message() {
    let cases = [
        ("std_cq_1500.wav", "CQ K1ABC FN42"),
        ("freetext_1500.wav", "TNX BOB 73 GL"),
        ("nonstd_cq_1500.wav", "CQ PJ4/K1ABC"),
        ("std_cq_0800.wav", "CQ K1ABC FN42"),
        ("std_cq_2400.wav", "CQ K1ABC FN42"),
        // Off the 3.125 Hz coarse grid: the coarse metric mislocates the carrier
        // by >1 tone, so this exercises the fine-refine window's ability to
        // recover it. (Codex adrev 2026-07-07, sync.rs fine_refine.)
        ("std_cq_1509_offgrid.wav", "CQ K1ABC FN42"),
    ];

    for (file, expected) in cases {
        let samples = load_fixture(file);
        let decodes = decode_samples(&samples, 12_000);
        // Zero-false ON THE FIXTURE ITSELF: a single-signal fixture must yield
        // EXACTLY one decode equal to the known message — not merely "contains it
        // among others". `any()` would pass even with spurious extra decodes and
        // so would not enforce the zero-false half of the hard-stop gate.
        let msgs: Vec<&str> = decodes.iter().map(|d| d.message.as_str()).collect();
        assert_eq!(msgs, vec![expected], "{file}: expected exactly one decode");
    }
}

/// The winning decode's sync metric clears the guard floor and its carrier is at
/// the right place — a spot check that the pipeline reports coherent metadata,
/// not just the right string.
#[test]
fn winning_candidate_metadata_is_coherent() {
    let samples = load_fixture("std_cq_1500.wav");
    let decodes = decode_samples(&samples, 12_000);
    let d = decodes
        .iter()
        .find(|d| d.message == "CQ K1ABC FN42")
        .expect("std_cq_1500 must decode");
    assert!(
        d.sync_metric >= tuxlink_ft8::sync::SYNC_FLOOR,
        "winning sync metric {} below floor",
        d.sync_metric
    );
    assert!((d.freq_hz - 1500.0).abs() <= 1.0, "carrier {} not ≈1500", d.freq_hz);
    assert!(
        (d.start_sample - 14160.0).abs() <= 60.0,
        "start {} not near centred frame 14160",
        d.start_sample
    );
}

/// ZERO false decodes: a silent slot and a pure-noise slot both yield no decode
/// (no candidate clears the sync-metric floor / CRC / converged guard).
#[test]
fn silence_and_noise_yield_no_decode() {
    // Synthesized silent buffer.
    let silence = vec![0.0f32; 180_000];
    assert!(
        decode_samples(&silence, 12_000).is_empty(),
        "silent slot produced a false decode"
    );

    // Sanity: the synthesized silent slot above faithfully models a real empty
    // capture — the fixture's leading 1.0 s (12000 samples) really is silence (the
    // centred frame does not start until sample 14160 = 1.18 s).
    let real = load_fixture("std_cq_1500.wav");
    assert!(
        real[..12_000].iter().all(|&s| s == 0.0),
        "fixture lead-in is not silent as documented"
    );

    // Deterministic white noise (test-only LCG) — no Costas structure.
    let mut state = 0x9E37_79B9u32;
    let noise: Vec<f32> = (0..180_000)
        .map(|_| {
            state = state.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
            (state >> 8) as f32 / (1u32 << 24) as f32 - 0.5
        })
        .collect();
    assert!(
        decode_samples(&noise, 12_000).is_empty(),
        "pure noise produced a false decode"
    );
}

/// Within-slot dedup on normalized message identity (plan T3.1 / WSJT-X multiset
/// semantics): two copies of the SAME message at well-separated carriers
/// (800 + 2400 Hz, 1600 Hz apart) summed into one slot must yield that message
/// EXACTLY ONCE. A frequency-only guard would report it twice (the carriers are
/// >4 Hz apart); message identity is the correct dedup key.
#[test]
fn same_message_at_two_carriers_dedups_to_one() {
    let a = load_fixture("std_cq_0800.wav");
    let b = load_fixture("std_cq_2400.wav");
    assert_eq!(a.len(), b.len());
    let mixed: Vec<f32> = a.iter().zip(b.iter()).map(|(x, y)| x + y).collect();
    let decodes = decode_samples(&mixed, 12_000);
    let msgs: Vec<&str> = decodes.iter().map(|d| d.message.as_str()).collect();
    assert_eq!(
        msgs,
        vec!["CQ K1ABC FN42"],
        "same message at two carriers must dedup to exactly one decode"
    );
}

/// Two DISTINCT messages in one slot both survive dedup (the dedup keys on
/// message identity, not frequency): a standard CQ at 1500 Hz summed with a
/// non-standard CQ at 800 Hz yields both messages. Guards against an
/// over-aggressive dedup that would collapse genuinely different signals.
#[test]
fn two_distinct_messages_in_one_slot_both_decode() {
    let nonstd = load_fixture("nonstd_cq_1500.wav"); // "CQ PJ4/K1ABC" at 1500 Hz
    let low = load_fixture("std_cq_0800.wav"); // "CQ K1ABC FN42" at 800 Hz
    assert_eq!(nonstd.len(), low.len());
    let mixed: Vec<f32> = nonstd.iter().zip(low.iter()).map(|(x, y)| x + y).collect();
    let decodes = decode_samples(&mixed, 12_000);
    let mut msgs: Vec<&str> = decodes.iter().map(|d| d.message.as_str()).collect();
    msgs.sort_unstable();
    assert_eq!(
        msgs,
        vec!["CQ K1ABC FN42", "CQ PJ4/K1ABC"],
        "two distinct messages must both decode"
    );
}
