//! rmcp tool router for the Tuxlink MCP server (phase 3.1).
//!
//! [`TuxlinkMcp`] is the rmcp handler. It owns the shared [`McpState`] and a
//! generated [`ToolRouter`]. Phase 3.1 registers exactly one tool —
//! [`TuxlinkMcp::server_info`] — a thin wrapper over the pure
//! [`server_info_view`](crate::server_info_view); all logic lives there so the
//! transport layer stays untested-by-design (it is exercised at tier-2).

use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::handler::server::ServerHandler;
use rmcp::model::{
    CallToolResult, Content, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo,
};
use rmcp::{tool, tool_handler, tool_router, ErrorData};

use crate::ports::{EgressPortError, PortError, SearchQueryDto, SessionIntentDto};
use crate::{server_info_view, McpState};

/// Map a [`PortError`] onto an rmcp tool error. Read tools surface the failure
/// to the agent rather than crashing the transport.
fn port_err(e: PortError) -> ErrorData {
    ErrorData::internal_error(e.to_string(), None)
}

/// Map an [`EgressPortError`] onto an rmcp tool error. A `Denied` is an
/// authorization refusal — surface it with a clear message telling the agent it
/// is not authorized to transmit (the operator must arm send authority, and the
/// session must not be tainted), distinct from an operational `Failed`.
fn egress_err(e: EgressPortError) -> ErrorData {
    match e {
        EgressPortError::Denied(reason) => ErrorData::invalid_request(
            format!(
                "not authorized to transmit: {reason}. The operator must ARM send \
                 authority, and the session must not be tainted (reading untrusted \
                 message content locks send authority until re-armed)."
            ),
            None,
        ),
        EgressPortError::Failed(reason) => ErrorData::internal_error(reason, None),
    }
}

/// The Tuxlink MCP server handler. Cloned per the rmcp serve loop; the inner
/// [`McpState`] is `Arc`-shared so all clones see the same live guard state.
#[derive(Clone)]
pub struct TuxlinkMcp {
    state: Arc<McpState>,
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl TuxlinkMcp {
    /// Build the handler around a shared [`McpState`]. `Self::tool_router()` is
    /// generated by the `#[tool_router]` macro from the `#[tool]` methods below.
    pub fn new(state: Arc<McpState>) -> Self {
        Self {
            state,
            tool_router: Self::tool_router(),
        }
    }

    /// Report the app identity and the live egress-authority state. Inert: it
    /// reads state only, never arms, taints, or egresses. The serializable shape
    /// is built by the pure [`server_info_view`]; this wrapper only encodes it
    /// into an rmcp tool result.
    #[tool(
        name = "server_info",
        description = "Report the Tuxlink app name/version and the live egress-authority state (armed, tainted). Read-only; does not transmit or change any state."
    )]
    pub async fn server_info(&self) -> Result<CallToolResult, ErrorData> {
        let dto = server_info_view(&self.state);
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    // ----- Status / diagnostics (no taint) -----

    #[tool(
        name = "backend_status",
        description = "Report the Winlink backend (CMS engine) connection status: connected, transport, and state. Read-only."
    )]
    pub async fn backend_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.backend_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "modem_get_status",
        description = "Report the current modem (ARDOP/VARA/packet) status: kind, connected, and state. Read-only."
    )]
    pub async fn modem_get_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.modem_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "vara_status",
        description = "Report VARA modem status: connected, bandwidth, and state. Read-only."
    )]
    pub async fn vara_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.vara_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "position_status",
        description = "Report the current position fix status and grid square (precision-reduced). Read-only."
    )]
    pub async fn position_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.position_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "platform_info",
        description = "Report host platform info (OS, arch, app version) for diagnostics. Read-only."
    )]
    pub async fn platform_info(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.platform_info().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "get_wizard_completed",
        description = "Report whether the first-run setup wizard has been completed. Read-only."
    )]
    pub async fn get_wizard_completed(&self) -> Result<CallToolResult, ErrorData> {
        let done = self.state.status.wizard_completed().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(done)?]))
    }

    #[tool(
        name = "p2p_peer_password_status",
        description = "Report whether a P2P peer password is Set (true) or NotSet (false) for the given callsign. Never returns the password itself. Read-only."
    )]
    pub async fn p2p_peer_password_status(
        &self,
        params: Parameters<CallsignParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(CallsignParams { callsign }) = params;
        let set = self
            .state
            .status
            .p2p_peer_password_status(&callsign)
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(set)?]))
    }

    // ----- Mailbox -----

    #[tool(
        name = "mailbox_list",
        description = "List message metadata in a mailbox folder. Returns untrusted message senders/subjects, so calling this taints the session (send authority is locked until the operator re-arms)."
    )]
    pub async fn mailbox_list(
        &self,
        params: Parameters<FolderParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(FolderParams { folder }) = params;
        let dto = self.state.mailbox.list(&folder).await.map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "message_read",
        description = "Read a parsed message (headers, body, attachment metadata) by folder + id. Returns untrusted content, so calling this taints the session."
    )]
    pub async fn message_read(
        &self,
        params: Parameters<MessageReadParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(MessageReadParams { folder, id }) = params;
        let dto = self
            .state
            .mailbox
            .read(&folder, &id)
            .await
            .map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "user_folders_list",
        description = "Enumerate mailbox folders and their message counts. Structural metadata; does not taint. Read-only."
    )]
    pub async fn user_folders_list(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.mailbox.folders().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    // ----- Search -----

    #[tool(
        name = "tauri_search_run",
        description = "Search mailbox messages by query, optionally scoped to a folder and limited. Returns untrusted message content, so calling this taints the session."
    )]
    pub async fn tauri_search_run(
        &self,
        params: Parameters<SearchParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(SearchParams {
            query,
            folder,
            limit,
        }) = params;
        let dto = self
            .state
            .search
            .messages(SearchQueryDto {
                query,
                folder,
                limit,
            })
            .await
            .map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "docs_search",
        description = "Search the in-app documentation by query. App-owned content; does not taint. Read-only."
    )]
    pub async fn docs_search(
        &self,
        params: Parameters<QueryParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(QueryParams { query }) = params;
        let dto = self.state.search.docs(&query).await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "catalog_list",
        description = "List the template/form catalog entries. App-owned content; does not taint. Read-only."
    )]
    pub async fn catalog_list(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.search.catalog().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    // ----- Config (curated, non-secret) -----

    #[tool(
        name = "config_read",
        description = "Read the curated, non-secret top-level config (CMS connect flag, transport, host, callsign, 4-char grid). Read-only; no passwords."
    )]
    pub async fn config_read(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.read().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "config_get_ardop",
        description = "Read the non-secret ARDOP modem config (host, port, drive level, bandwidth). Read-only."
    )]
    pub async fn config_get_ardop(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.ardop().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "config_get_vara",
        description = "Read the non-secret VARA modem config (host, port, bandwidth, drive level). Read-only; no VARA license secrets."
    )]
    pub async fn config_get_vara(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.vara().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "packet_config_get",
        description = "Read the non-secret packet (AX.25/KISS) config (KISS host/port, baud, TX delay). Read-only."
    )]
    pub async fn packet_config_get(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.packet().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    // ----- Devices -----

    #[tool(
        name = "packet_list_serial_devices",
        description = "Enumerate serial devices available for a TNC/CAT connection. Read-only."
    )]
    pub async fn packet_list_serial_devices(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.devices.serial().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "packet_list_bluetooth_devices",
        description = "Enumerate Bluetooth devices (names + minimized MACs). Read-only."
    )]
    pub async fn packet_list_bluetooth_devices(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.devices.bluetooth().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    #[tool(
        name = "ardop_list_audio_devices",
        description = "Enumerate capture + playback audio devices for modem audio selection. Read-only."
    )]
    pub async fn ardop_list_audio_devices(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.devices.audio().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    // ----- Logs -----

    #[tool(
        name = "session_log_snapshot",
        description = "Snapshot the current session log. May contain untrusted wire content, so calling this taints the session."
    )]
    pub async fn session_log_snapshot(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.logs.snapshot().await.map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![Content::json(dto)?]))
    }

    // ----- GATED egress (require armed send authority; deny when tainted) -----
    //
    // These tools transmit/connect (egress). The IMPL gates each call through
    // `guarded_egress(.., Agent, ..)`; the tool itself is a thin adapter that
    // maps an EgressPortError::Denied onto an authorization-shaped tool error.
    // They do NOT call `guard.taint()` — the gate READS taint; the reading tier
    // SETS it.

    #[tool(
        name = "cms_connect",
        description = "Connect to the configured CMS (Winlink common message server). EGRESS: requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn cms_connect(&self) -> Result<CallToolResult, ErrorData> {
        self.state.egress.cms_connect().await.map_err(egress_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "verify_cms_connection",
        description = "Verify the live CMS connection with a network round-trip. EGRESS: requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn verify_cms_connection(&self) -> Result<CallToolResult, ErrorData> {
        self.state
            .egress
            .verify_cms_connection()
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "ardop_connect",
        description = "Connect the ARDOP modem to a target station. EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn ardop_connect(
        &self,
        params: Parameters<TargetParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(TargetParams { target }) = params;
        self.state
            .egress
            .ardop_connect(target)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "ardop_b2f_exchange",
        description = "Run an ARDOP B2F message exchange with a target for the given routing intent (cms/radio-only/post-office/mesh/p2p; defaults to cms). EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn ardop_b2f_exchange(
        &self,
        params: Parameters<ExchangeParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(ExchangeParams { target, intent }) = params;
        self.state
            .egress
            .ardop_b2f_exchange(target, intent)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "vara_b2f_exchange",
        description = "Run a VARA B2F message exchange with a target for the given routing intent (cms/radio-only/post-office/mesh/p2p; defaults to cms). EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn vara_b2f_exchange(
        &self,
        params: Parameters<ExchangeParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(ExchangeParams { target, intent }) = params;
        self.state
            .egress
            .vara_b2f_exchange(target, intent)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "packet_connect",
        description = "Connect an AX.25 packet session to a callsign over an optional digipeater path. EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn packet_connect(
        &self,
        params: Parameters<PacketConnectParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(PacketConnectParams { call, path }) = params;
        self.state
            .egress
            .packet_connect(call, path)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    // ----- UNGATED abort (stopping is ALWAYS allowed) -----
    //
    // Pure-stop tools. Never gated by armed/taint state: a working abort is a
    // safety primitive, so the agent can always halt a transmission/connection.

    #[tool(
        name = "cms_abort",
        description = "Abort/disconnect the CMS connection. Stopping is always allowed (never gated)."
    )]
    pub async fn cms_abort(&self) -> Result<CallToolResult, ErrorData> {
        self.state.abort.cms_abort().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "modem_ardop_disconnect",
        description = "Disconnect the ARDOP modem. Stopping is always allowed (never gated)."
    )]
    pub async fn modem_ardop_disconnect(&self) -> Result<CallToolResult, ErrorData> {
        self.state.abort.ardop_disconnect().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }

    #[tool(
        name = "vara_stop_session",
        description = "Stop the active VARA session. Stopping is always allowed (never gated)."
    )]
    pub async fn vara_stop_session(&self) -> Result<CallToolResult, ErrorData> {
        self.state
            .abort
            .vara_stop_session()
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![Content::json("ok")?]))
    }
}

/// `{ "callsign": "W1AW" }` — input for `p2p_peer_password_status`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct CallsignParams {
    /// The peer station callsign to check.
    pub callsign: String,
}

/// `{ "folder": "Inbox" }` — input for `mailbox_list`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct FolderParams {
    /// The mailbox folder name to list.
    pub folder: String,
}

/// `{ "folder": "Inbox", "id": "MSG001" }` — input for `message_read`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct MessageReadParams {
    /// The folder the message lives in.
    pub folder: String,
    /// The message id to read.
    pub id: String,
}

/// `{ "query": "...", "folder": null, "limit": null }` — input for
/// `tauri_search_run`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct SearchParams {
    /// The search query string.
    pub query: String,
    /// Optional folder to scope the search to.
    #[serde(default)]
    pub folder: Option<String>,
    /// Optional maximum number of results to return.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// `{ "query": "..." }` — input for `docs_search`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct QueryParams {
    /// The documentation search query string.
    pub query: String,
}

/// `{ "target": "KX4Z-10" }` — input for `ardop_connect`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct TargetParams {
    /// The target station/gateway callsign to connect to.
    pub target: String,
}

/// `{ "target": "KX4Z", "intent": "cms" }` — input for the B2F exchange tools.
/// `intent` selects the routing pool ([`SessionIntentDto`]:
/// `cms` / `radio-only` / `post-office` / `mesh` / `p2p`) and defaults to
/// [`SessionIntentDto::Cms`] when omitted.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ExchangeParams {
    /// The target station/gateway callsign.
    pub target: String,
    /// The routing pool for the exchange; defaults to `cms` when omitted.
    #[serde(default)]
    pub intent: SessionIntentDto,
}

/// `{ "call": "W1AW-5", "path": ["WIDE1-1"] }` — input for `packet_connect`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct PacketConnectParams {
    /// The destination station callsign.
    pub call: String,
    /// Optional ordered digipeater path; empty for a direct connection.
    #[serde(default)]
    pub path: Vec<String>,
}

#[tool_handler]
impl ServerHandler for TuxlinkMcp {
    // Build `ServerInfo` (= `InitializeResult`) from `default()` then set the
    // fields we care about. clippy's `field_reassign_with_default` must be
    // allowed at the FN level: a statement-level allow on the `let` does NOT
    // cover the lint's span and CI's clippy still fired (PR #911 first verify).
    #[allow(clippy::field_reassign_with_default)]
    fn get_info(&self) -> ServerInfo {
        let mut info = ServerInfo::default();
        info.protocol_version = ProtocolVersion::LATEST;
        info.capabilities = ServerCapabilities::builder().enable_tools().build();
        info.server_info = Implementation::from_build_env();
        info.instructions = Some(
            "Tuxlink MCP server. Read-only tools report app/backend/modem status, \
             mailbox + search content, curated config, devices, and the session log. \
             Tools that return untrusted external content (mailbox_list, message_read, \
             tauri_search_run, session_log_snapshot) taint the session, locking send \
             authority until the operator re-arms."
                .to_string(),
        );
        info
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicBool, Ordering};

    use crate::ports::{MessageMetaDto, ParsedMessageDto};
    use crate::test_support::{
        state_with_egress_probes, state_with_guard, SEED_MSG_FROM, SEED_MSG_ID, SEED_MSG_SUBJECT,
    };
    use tuxlink_security::EgressGuard;

    fn handler() -> TuxlinkMcp {
        TuxlinkMcp::new(Arc::new(state_with_guard(EgressGuard::new())))
    }

    /// Deterministic clock so an armed grant is un-expired within the test.
    fn fixed_1000() -> u64 {
        1000
    }

    /// Build a handler plus the egress `op_ran` + `aborted` probe flags, all
    /// sharing one guard (on a fixed clock so arm() is live).
    fn handler_with_probes() -> (TuxlinkMcp, Arc<AtomicBool>, Arc<AtomicBool>) {
        let (state, op_ran, aborted) =
            state_with_egress_probes(EgressGuard::with_clock(fixed_1000));
        (TuxlinkMcp::new(Arc::new(state)), op_ran, aborted)
    }

    /// Extract + deserialize the JSON the tool packed into its first text
    /// content. `Content::json` serializes to a text content carrying the JSON.
    fn json_of<T: serde::de::DeserializeOwned>(result: &CallToolResult) -> T {
        let text = result.content[0]
            .as_text()
            .expect("tool result must be a JSON text content")
            .text
            .clone();
        serde_json::from_str(&text).expect("tool JSON must deserialize back into the DTO")
    }

    // --- TAINT tools flip the guard ---

    #[tokio::test]
    async fn mailbox_list_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.mailbox_list(Parameters(FolderParams {
            folder: "Inbox".into(),
        }))
        .await
        .unwrap();
        assert!(h.state.guard.is_tainted(), "mailbox_list must taint");
    }

    #[tokio::test]
    async fn message_read_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.message_read(Parameters(MessageReadParams {
            folder: "Inbox".into(),
            id: SEED_MSG_ID.into(),
        }))
        .await
        .unwrap();
        assert!(h.state.guard.is_tainted(), "message_read must taint");
    }

    #[tokio::test]
    async fn tauri_search_run_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.tauri_search_run(Parameters(SearchParams {
            query: "ares".into(),
            folder: None,
            limit: None,
        }))
        .await
        .unwrap();
        assert!(h.state.guard.is_tainted(), "tauri_search_run must taint");
    }

    #[tokio::test]
    async fn session_log_snapshot_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.session_log_snapshot().await.unwrap();
        assert!(
            h.state.guard.is_tainted(),
            "session_log_snapshot must taint"
        );
    }

    // --- NON-taint tools leave a fresh guard clean ---

    #[tokio::test]
    async fn non_taint_tools_do_not_taint() {
        let h = handler();
        h.backend_status().await.unwrap();
        h.config_read().await.unwrap();
        h.platform_info().await.unwrap();
        h.docs_search(Parameters(QueryParams {
            query: "start".into(),
        }))
        .await
        .unwrap();
        h.user_folders_list().await.unwrap();
        h.catalog_list().await.unwrap();
        h.packet_list_serial_devices().await.unwrap();
        h.p2p_peer_password_status(Parameters(CallsignParams {
            callsign: "W1AW".into(),
        }))
        .await
        .unwrap();
        assert!(
            !h.state.guard.is_tainted(),
            "read-only status/config/docs/devices tools must NOT taint a fresh guard"
        );
    }

    // --- DTO round-trips through the tool result ---

    #[tokio::test]
    async fn message_read_round_trips_dto() {
        let h = handler();
        let result = h
            .message_read(Parameters(MessageReadParams {
                folder: "Inbox".into(),
                id: SEED_MSG_ID.into(),
            }))
            .await
            .unwrap();
        let dto: ParsedMessageDto = json_of(&result);
        assert_eq!(dto.id, SEED_MSG_ID);
        assert_eq!(dto.from, SEED_MSG_FROM);
        assert_eq!(dto.subject, SEED_MSG_SUBJECT);
    }

    #[tokio::test]
    async fn mailbox_list_round_trips_dto() {
        let h = handler();
        let result = h
            .mailbox_list(Parameters(FolderParams {
                folder: "Inbox".into(),
            }))
            .await
            .unwrap();
        let items: Vec<MessageMetaDto> = json_of(&result);
        assert_eq!(items.len(), 1);
        assert_eq!(items[0].from, SEED_MSG_FROM);
        assert_eq!(items[0].subject, SEED_MSG_SUBJECT);
    }

    #[tokio::test]
    async fn config_read_round_trips_grid() {
        let h = handler();
        let result = h.config_read().await.unwrap();
        let dto: crate::ports::ConfigViewDto = json_of(&result);
        assert_eq!(dto.grid, "CN87", "grid must be the 4-char fixture value");
    }

    // --- STEP 6: egress gate + injection-containment via the real tools ---

    #[tokio::test]
    async fn gated_egress_on_unarmed_guard_denies_and_op_never_runs() {
        let (h, op_ran, _aborted) = handler_with_probes();
        // Fresh guard is unarmed → the gated egress tool must be denied.
        let err = h.cms_connect().await.expect_err("unarmed must deny");
        assert!(
            err.message.contains("not authorized"),
            "denial message must name the missing authorization, got: {}",
            err.message
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "the underlying egress op must NEVER run when denied"
        );
    }

    #[tokio::test]
    async fn gated_egress_after_arm_is_allowed_and_op_runs() {
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.arm(30); // arm send authority (deadline 1030, now 1000)
        h.cms_connect().await.expect("armed + untainted must allow");
        assert!(
            op_ran.load(Ordering::SeqCst),
            "the underlying egress op must run once authorized"
        );
    }

    #[tokio::test]
    async fn gated_egress_denied_when_tainted_even_if_armed() {
        // Simulate a prior malicious read tainting the session, then arming.
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.taint(); // a prior message_read/search tainted the session
        h.state.guard.arm(30); // arming does NOT clear taint
        let err = h
            .ardop_connect(Parameters(TargetParams {
                target: "KX4Z-10".into(),
            }))
            .await
            .expect_err("tainted must deny even when armed");
        assert!(err.message.contains("not authorized"));
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "a tainted session must not transmit even while armed"
        );
    }

    #[tokio::test]
    async fn gated_egress_allowed_after_clear_taint_and_fresh_arm() {
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.taint();
        h.state.guard.clear_taint(); // explicit session reset
        h.state.guard.arm(30);
        h.vara_b2f_exchange(Parameters(ExchangeParams {
            target: "KX4Z".into(),
            intent: SessionIntentDto::Cms,
        }))
        .await
        .expect("fresh arm after clear_taint must allow");
        assert!(op_ran.load(Ordering::SeqCst), "op must run after a clean re-arm");
    }

    #[tokio::test]
    async fn abort_tool_succeeds_regardless_of_guard_state() {
        // Unarmed + tainted: the abort tool must STILL succeed (never gated).
        let (h, _op_ran, aborted) = handler_with_probes();
        h.state.guard.taint(); // hostile state
        h.cms_abort().await.expect("abort is never gated");
        assert!(
            aborted.load(Ordering::SeqCst),
            "the underlying abort must fire regardless of guard state"
        );
    }

    #[tokio::test]
    async fn all_abort_tools_succeed_when_tainted_and_unarmed() {
        let (h, _op_ran, aborted) = handler_with_probes();
        h.state.guard.taint();
        h.cms_abort().await.unwrap();
        h.modem_ardop_disconnect().await.unwrap();
        h.vara_stop_session().await.unwrap();
        assert!(aborted.load(Ordering::SeqCst));
    }
}
