//! rmcp tool router for the Tuxlink MCP server (phase 3.1).
//!
//! [`TuxlinkMcp`] is the rmcp handler. It owns the shared [`McpState`] and a
//! generated [`ToolRouter`]. Phase 3.1 registers exactly one tool —
//! [`TuxlinkMcp::server_info`] — a thin wrapper over the pure
//! [`server_info_view`](crate::server_info_view); all logic lives there so the
//! transport layer stays untested-by-design (it is exercised at tier-2).

use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::handler::server::ServerHandler;
use rmcp::model::{
    CallToolResult, ContentBlock, GetPromptRequestParam, GetPromptResult, ListPromptsResult,
    ListResourcesResult, PaginatedRequestParam, Prompt, PromptArgument, PromptMessage,
    ReadResourceRequestParam, ReadResourceResult, Resource, ResourceContents, Role,
    ServerCapabilities, ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{tool, tool_handler, tool_router, ErrorData, RoleServer};

use crate::content;
use crate::ports::{
    ArdopWriteDto, ComposeDraftDto, EgressPortError, GribRequestDto, PacketWriteDto, PortError,
    PredictRequestDto, QsyCandidateDto, SearchQueryDto, SendFormDto, SessionIntentDto,
    StationFilterDto, VaraWriteDto, WritePortError,
};
use crate::{server_info_view, McpState};

/// The MIME type all knowledge resources are served as.
const KNOWLEDGE_MIME: &str = "text/markdown";

/// Map a [`PortError`] onto an rmcp tool error. Read tools surface the failure
/// to the agent rather than crashing the transport.
fn port_err(e: PortError) -> ErrorData {
    ErrorData::internal_error(e.to_string(), None)
}

/// Map an [`EgressPortError`] onto an rmcp tool error. A `Denied` is an
/// authorization refusal — surface it with a clear message telling the agent it
/// is not authorized to transmit (the operator must arm send authority, and the
/// session must not be tainted), distinct from an operational `Failed`.
fn egress_err(e: EgressPortError) -> ErrorData {
    match e {
        EgressPortError::Denied(reason) => ErrorData::invalid_request(
            format!(
                "not authorized to transmit: {reason}. The operator must ARM send \
                 authority, and the session must not be tainted (reading untrusted \
                 message content locks send authority until re-armed)."
            ),
            None,
        ),
        EgressPortError::Failed(reason) => ErrorData::internal_error(reason, None),
    }
}

/// Map a [`WritePortError`] onto an rmcp tool error. `Denied` is an
/// authorization refusal (write tier only) and reuses the egress-denial message
/// shape; `Invalid` is a malformed-request rejection (surfaced even when
/// disarmed, before the gate); `Failed` is an operational error.
fn write_err(e: WritePortError) -> ErrorData {
    match e {
        WritePortError::Denied(reason) => ErrorData::invalid_request(
            format!(
                "not authorized to write: {reason}. The operator must ARM send \
                 authority, and the session must not be tainted (reading untrusted \
                 message content locks send authority until re-armed)."
            ),
            None,
        ),
        WritePortError::Invalid(reason) => ErrorData::invalid_request(reason, None),
        WritePortError::Failed(reason) => ErrorData::internal_error(reason, None),
    }
}

/// The Tuxlink MCP server handler. Cloned per the rmcp serve loop; the inner
/// [`McpState`] is `Arc`-shared so all clones see the same live guard state.
#[derive(Clone)]
pub struct TuxlinkMcp {
    state: Arc<McpState>,
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl TuxlinkMcp {
    /// Build the handler around a shared [`McpState`]. `Self::tool_router()` is
    /// generated by the `#[tool_router]` macro from the `#[tool]` methods below.
    pub fn new(state: Arc<McpState>) -> Self {
        Self {
            state,
            tool_router: Self::tool_router(),
        }
    }

    /// Report the app identity and the live egress-authority state. Inert: it
    /// reads state only, never arms, taints, or egresses. The serializable shape
    /// is built by the pure [`server_info_view`]; this wrapper only encodes it
    /// into an rmcp tool result.
    #[tool(
        name = "server_info",
        description = "Report the operator's SEND-AUTHORITY state — whether send authority is currently ARMED (armed=true means you MAY transmit; false means you may only stage), how many seconds of the armed window remain, and whether the session is TAINTED (which locks sending) — plus the Tuxlink app name/version. Call this to check whether you are authorized to transmit right now, e.g. before deciding whether to connect+send or to stage-and-report. Read-only; does not transmit or change any state."
    )]
    pub async fn server_info(&self) -> Result<CallToolResult, ErrorData> {
        let dto = server_info_view(&self.state);
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Status / diagnostics (no taint) -----

    #[tool(
        name = "backend_status",
        description = "Report the Winlink backend (CMS engine) connection status: connected, transport, and state. Read-only. Does NOT report send authority — call server_info to check whether transmitting is currently armed."
    )]
    pub async fn backend_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.backend_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "modem_get_status",
        description = "Report the current modem (ARDOP/VARA/packet) status: kind, connected, and state. Read-only."
    )]
    pub async fn modem_get_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.modem_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "vara_status",
        description = "Report VARA modem status: connected, bandwidth, and state. Read-only."
    )]
    pub async fn vara_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.vara_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "position_status",
        description = "Report THE OPERATOR'S current station location — their Maidenhead grid square (precision-reduced to ~4 chars for privacy) and GPS fix status. Call this to answer 'where am I', 'what's near me', or any location-relative question — do NOT ask the operator for their location; Tuxlink already knows it. Read-only."
    )]
    pub async fn position_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.position_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "platform_info",
        description = "Report host platform info (OS, arch, app version) for diagnostics. Read-only."
    )]
    pub async fn platform_info(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.platform_info().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "rig_status",
        description = "Report the rig's configured state and, best-effort, its live VFO frequency/mode/PTT via a transient rigctld read (never transmits; may report nulls if the rig is unconfigured or its serial is busy with an active session). Read-only."
    )]
    pub async fn rig_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.status.rig_status().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "get_wizard_completed",
        description = "Report whether the first-run setup wizard has been completed. Read-only."
    )]
    pub async fn get_wizard_completed(&self) -> Result<CallToolResult, ErrorData> {
        let done = self.state.status.wizard_completed().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(done)?]))
    }

    #[tool(
        name = "p2p_peer_password_status",
        description = "Report whether a P2P peer password is Set (true) or NotSet (false) for the given callsign. Never returns the password itself. Read-only."
    )]
    pub async fn p2p_peer_password_status(
        &self,
        params: Parameters<CallsignParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(CallsignParams { callsign }) = params;
        let set = self
            .state
            .status
            .p2p_peer_password_status(&callsign)
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(set)?]))
    }

    // ----- Mailbox -----

    #[tool(
        name = "mailbox_list",
        description = "List message metadata in a mailbox folder. Returns untrusted message senders/subjects, so calling this taints the session (send authority is locked until the operator re-arms)."
    )]
    pub async fn mailbox_list(
        &self,
        params: Parameters<FolderParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(FolderParams { folder }) = params;
        let dto = self.state.mailbox.list(&folder).await.map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "message_read",
        description = "Read a parsed message (headers, body, attachment metadata) by folder + id. Returns untrusted content, so calling this taints the session."
    )]
    pub async fn message_read(
        &self,
        params: Parameters<MessageReadParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(MessageReadParams { folder, id }) = params;
        let dto = self
            .state
            .mailbox
            .read(&folder, &id)
            .await
            .map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "user_folders_list",
        description = "Enumerate mailbox folders and their message counts. Structural metadata; does not taint. Read-only."
    )]
    pub async fn user_folders_list(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.mailbox.folders().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Search -----

    #[tool(
        name = "tauri_search_run",
        description = "Search mailbox messages by query, optionally scoped to a folder and limited. Returns untrusted message content, so calling this taints the session."
    )]
    pub async fn tauri_search_run(
        &self,
        params: Parameters<SearchParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(SearchParams {
            query,
            folder,
            limit,
        }) = params;
        let dto = self
            .state
            .search
            .messages(SearchQueryDto {
                query,
                folder,
                limit,
            })
            .await
            .map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "docs_search",
        description = "Search the in-app documentation by query. App-owned content; does not taint. Read-only."
    )]
    pub async fn docs_search(
        &self,
        params: Parameters<QueryParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(QueryParams { query }) = params;
        let dto = self.state.search.docs(&query).await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "catalog_list",
        description = "List the Winlink Request Center query catalog: the on-demand products the operator can request over Winlink. Hundreds of items across categories such as PROPAGATION (HF propagation forecasts), METAR (airport weather), SAT_KEPS (satellite keplerian elements), AURORA, marine/ice forecasts, and ARES/RACES bulletins. Each entry has a category, a filename id (pass these ids to catalog_send_inquiry to stage a request), and a description. This is what to browse to answer 'what can I pull/request from the Request Center'; it is NOT limited to weather/GRIB. App-owned content; does not taint. Read-only."
    )]
    pub async fn catalog_list(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.search.catalog().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Config (curated, non-secret) -----

    #[tool(
        name = "config_read",
        description = "Read the curated, non-secret top-level config (CMS connect flag, transport, host, callsign, 4-char grid). Read-only; no passwords."
    )]
    pub async fn config_read(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.read().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "config_get_ardop",
        description = "Read the non-secret ARDOP modem config (host, port, drive level, bandwidth). Read-only."
    )]
    pub async fn config_get_ardop(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.ardop().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "config_get_vara",
        description = "Read the non-secret VARA modem config (host, port, bandwidth, drive level). Read-only; no VARA license secrets."
    )]
    pub async fn config_get_vara(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.vara().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "packet_config_get",
        description = "Read the non-secret packet (AX.25/KISS) config (KISS host/port, baud, TX delay). Read-only."
    )]
    pub async fn packet_config_get(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.packet().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "config_get_rig",
        description = "Read the non-secret radio-level rig config (hamlib model, rigctld endpoint, CAT serial, close-serial/live-vfo/qsy flags). Read-only; no secrets."
    )]
    pub async fn config_get_rig(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.config.rig().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Devices -----

    #[tool(
        name = "packet_list_serial_devices",
        description = "Enumerate serial devices available for a TNC/CAT connection. Read-only."
    )]
    pub async fn packet_list_serial_devices(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.devices.serial().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "packet_list_bluetooth_devices",
        description = "Enumerate Bluetooth devices (names + minimized MACs). Read-only."
    )]
    pub async fn packet_list_bluetooth_devices(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.devices.bluetooth().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "ardop_list_audio_devices",
        description = "Enumerate capture + playback audio devices for modem audio selection. Read-only."
    )]
    pub async fn ardop_list_audio_devices(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.devices.audio().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Logs -----

    #[tool(
        name = "session_log_snapshot",
        description = "Snapshot the current session log. May contain untrusted wire content, so calling this taints the session."
    )]
    pub async fn session_log_snapshot(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.logs.snapshot().await.map_err(port_err)?;
        self.state.guard.taint();
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Station intelligence (inert reads; no taint, no gate) -----
    //
    // These three tools call a read-only port and JSON-encode the result. They
    // serve public/cached directory data and offline propagation/space-weather
    // computation — no untrusted external message content and no transmission —
    // so they NEITHER taint the session NOR pass through the egress gate.

    #[tool(
        name = "find_stations",
        description = "List Winlink RMS gateways for the given transports/bands (callsign, frequencies, grid). Each gateway also carries distance_km, distance_mi, and bearing_deg from your station's grid (all null when your grid is unset — see operator_grid on the result); gateways are sorted nearest-first, unknown-distance last. Public directory data, cached. Read-only; does not transmit."
    )]
    pub async fn find_stations(
        &self,
        params: Parameters<StationFilterParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(StationFilterParams {
            modes,
            history_hours,
            bands,
        }) = params;
        let dto = self
            .state
            .stations
            .find_stations(StationFilterDto {
                modes,
                history_hours,
                bands,
            })
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "predict_path",
        description = "Predict HF path reliability/SNR/MUFday by UTC hour from your station to a target grid across the given dials. Offline VOACAP. Read-only."
    )]
    pub async fn predict_path(
        &self,
        params: Parameters<PredictRequestParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(PredictRequestParams {
            rx_grid,
            frequencies_khz,
            gateway_antenna,
        }) = params;
        let dto = self
            .state
            .prediction
            .predict_path(PredictRequestDto {
                rx_grid,
                frequencies_khz,
                gateway_antenna,
            })
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "solar_conditions",
        description = "Report current space-weather indices (SFI/A/K) + the sunspot number used for predictions. Public data. Read-only."
    )]
    pub async fn solar_conditions(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self.state.prediction.solar().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- Provisioning: VARA-under-WINE setup (tuxlink-w7212) -----
    //
    // Two read-only probes plus the one-time install action. The probes are
    // inert reads (no taint, no gate). `vara_install_start` is NON-TRANSMIT — it
    // installs software (apt/winetricks/wine) and never keys a radio — so it does
    // NOT pass through the transmit consent gate; the operator-presence guard is
    // the engine's own pkexec OS password prompt.

    #[tool(
        name = "vara_engine_available",
        description = "Report whether this Tuxlink build bundles the VARA-under-WINE setup engine (true means vara_install_start can run here). x86_64 Linux only. Read-only; does not transmit."
    )]
    pub async fn vara_engine_available(&self) -> Result<CallToolResult, ErrorData> {
        let available = self
            .state
            .provision
            .vara_engine_available()
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(available)?]))
    }

    #[tool(
        name = "vara_install_status",
        description = "Probe whether VARA HF is already provisioned under WINE on this host: returns `ready` plus each install-pipeline checkpoint's state (deps -> prefix -> vara -> vb6 -> ocx -> verify -> autostart). Offline and read-only — never launches VARA, never touches the network, never transmits. Read tuxlink://playbook/vara-wine-setup for the full workflow."
    )]
    pub async fn vara_install_status(&self) -> Result<CallToolResult, ErrorData> {
        let dto = self
            .state
            .provision
            .vara_install_status()
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    #[tool(
        name = "vara_install_start",
        description = "Install VARA HF under WINE from a user-supplied installer .exe path (x86_64 Linux only). This runs a PRIVILEGED install: pkexec prompts the OPERATOR for their OS password at the machine — you cannot supply it. NON-TRANSMIT: it provisions software (apt/winetricks/wine) and never keys a radio, so it does NOT require armed send authority. The operator must FIRST download the proprietary VARA .exe themselves (rosmodem / winlink.org) — Tuxlink cannot bundle it. Read tuxlink://playbook/vara-wine-setup FIRST, then call vara_engine_available + vara_install_status to check state before invoking this. Runs for several minutes and returns the final install summary."
    )]
    pub async fn vara_install_start(
        &self,
        params: Parameters<VaraInstallParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(VaraInstallParams { installer_path }) = params;
        let dto = self
            .state
            .provision
            .vara_install_start(installer_path)
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(dto)?]))
    }

    // ----- GATED egress (require armed send authority; deny when tainted) -----
    //
    // These tools transmit/connect (egress). The IMPL gates each call through
    // `guarded_egress(.., Agent, ..)`; the tool itself is a thin adapter that
    // maps an EgressPortError::Denied onto an authorization-shaped tool error.
    // They do NOT call `guard.taint()` — the gate READS taint; the reading tier
    // SETS it.

    #[tool(
        name = "cms_connect",
        description = "Connect to the configured CMS (Winlink common message server). EGRESS: requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn cms_connect(&self) -> Result<CallToolResult, ErrorData> {
        self.state.egress.cms_connect().await.map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "verify_cms_connection",
        description = "Verify the live CMS connection with a network round-trip. EGRESS: requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn verify_cms_connection(&self) -> Result<CallToolResult, ErrorData> {
        self.state
            .egress
            .verify_cms_connection()
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "rig_tune",
        description = "Tune the rig to a frequency (set VFO + data mode) over CAT. EGRESS (commands the radio — same authority class as a transmit): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn rig_tune(
        &self,
        params: Parameters<RigTuneParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(RigTuneParams { freq_hz }) = params;
        self.state.egress.rig_tune(freq_hz).await.map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "ardop_connect",
        description = "Connect the ARDOP modem to a target station. Optional freq_hz pre-tunes the rig over CAT for the dial; optional qsy_candidates supplies an ordered frequency walk (operator-gated). EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn ardop_connect(
        &self,
        params: Parameters<TargetParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(TargetParams {
            target,
            freq_hz,
            qsy_candidates,
        }) = params;
        self.state
            .egress
            .ardop_connect(target, freq_hz, qsy_candidates)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "ardop_b2f_exchange",
        description = "Run an ARDOP B2F message exchange with a target for the given routing intent (cms/radio-only/post-office/mesh/p2p; defaults to cms). The ARDOP link is tuned at connect, so this carries no frequency/QSY params. EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn ardop_b2f_exchange(
        &self,
        params: Parameters<ExchangeParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(ExchangeParams { target, intent }) = params;
        self.state
            .egress
            .ardop_b2f_exchange(target, intent)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "vara_b2f_exchange",
        description = "Run a VARA B2F message exchange with a target for the given routing intent (cms/radio-only/post-office/mesh/p2p; defaults to cms). Optional freq_hz / qsy_candidates pre-tune + QSY-walk the dial (VARA connects + tunes + exchanges in one call). EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn vara_b2f_exchange(
        &self,
        params: Parameters<VaraExchangeParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(VaraExchangeParams {
            target,
            intent,
            freq_hz,
            qsy_candidates,
        }) = params;
        self.state
            .egress
            .vara_b2f_exchange(target, intent, freq_hz, qsy_candidates)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "packet_connect",
        description = "Connect an AX.25 packet session to a callsign over an optional digipeater path. EGRESS (keys the transmitter): requires armed send-authority and an un-tainted session; denied otherwise."
    )]
    pub async fn packet_connect(
        &self,
        params: Parameters<PacketConnectParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(PacketConnectParams { call, path }) = params;
        self.state
            .egress
            .packet_connect(call, path)
            .await
            .map_err(egress_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    // ----- UNGATED abort (stopping is ALWAYS allowed) -----
    //
    // Pure-stop tools. Never gated by armed/taint state: a working abort is a
    // safety primitive, so the agent can always halt a transmission/connection.

    #[tool(
        name = "cms_abort",
        description = "Abort/disconnect the CMS connection. Stopping is always allowed (never gated)."
    )]
    pub async fn cms_abort(&self) -> Result<CallToolResult, ErrorData> {
        self.state.abort.cms_abort().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "modem_ardop_disconnect",
        description = "Disconnect the ARDOP modem. Stopping is always allowed (never gated)."
    )]
    pub async fn modem_ardop_disconnect(&self) -> Result<CallToolResult, ErrorData> {
        self.state.abort.ardop_disconnect().await.map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "vara_stop_session",
        description = "Stop the active VARA session. Stopping is always allowed (never gated)."
    )]
    pub async fn vara_stop_session(&self) -> Result<CallToolResult, ErrorData> {
        self.state
            .abort
            .vara_stop_session()
            .await
            .map_err(port_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    // ----- GATED writes (mutate config/state; require armed send authority) -----
    //
    // These tools mutate config/mailbox state. The IMPL validates the input
    // FIRST (an `Invalid` is returned even when disarmed, never consuming the
    // armed grant) and then gates the mutation through `guarded_egress(.., Agent,
    // ..)`. The tool is a thin adapter mapping a `WritePortError` onto a tool
    // error (Denied → not-authorized, Invalid → invalid_request, Failed →
    // internal_error). They do NOT taint.

    #[tool(
        name = "config_set_ardop",
        description = "Set the ARDOP drive level (0..=100). WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise. An out-of-range value is rejected as invalid even when disarmed."
    )]
    pub async fn config_set_ardop(
        &self,
        params: Parameters<ArdopWriteParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(ArdopWriteParams { drive_level }) = params;
        self.state
            .write
            .set_ardop(ArdopWriteDto { drive_level })
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "config_set_vara",
        description = "Set the VARA bandwidth in Hz (500/2300/2750). WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise. An out-of-range value is rejected as invalid even when disarmed."
    )]
    pub async fn config_set_vara(
        &self,
        params: Parameters<VaraWriteParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(VaraWriteParams { bandwidth_hz }) = params;
        self.state
            .write
            .set_vara(VaraWriteDto { bandwidth_hz })
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "packet_config_set",
        description = "Set the packet (AX.25/KISS) connection params (ssid, tcp host/port, tx delay). WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn packet_config_set(
        &self,
        params: Parameters<PacketWriteParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(PacketWriteParams {
            ssid,
            tcp_host,
            tcp_port,
            txdelay_ms,
        }) = params;
        self.state
            .write
            .set_packet(PacketWriteDto {
                ssid,
                tcp_host,
                tcp_port,
                txdelay_ms,
            })
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "config_set_grid",
        description = "Set the station grid square (Maidenhead locator). WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn config_set_grid(
        &self,
        params: Parameters<GridParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(GridParams { grid }) = params;
        self.state.write.set_grid(grid).await.map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "position_set_source",
        description = "Set the position source (e.g. gps/manual). WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn position_set_source(
        &self,
        params: Parameters<PositionSourceParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(PositionSourceParams { source }) = params;
        self.state
            .write
            .set_position_source(source)
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "config_set_privacy",
        description = "Set the GPS privacy: broadcast state + position precision. WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn config_set_privacy(
        &self,
        params: Parameters<PrivacyParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(PrivacyParams {
            gps_state,
            precision,
        }) = params;
        self.state
            .write
            .set_privacy(gps_state, precision)
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "packet_set_listen",
        description = "Enable or disable packet listen mode. WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn packet_set_listen(
        &self,
        params: Parameters<ListenParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(ListenParams { enabled }) = params;
        self.state
            .write
            .set_packet_listen(enabled)
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "mailbox_move",
        description = "Move a message between mailbox folders. WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn mailbox_move(
        &self,
        params: Parameters<MailboxMoveParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(MailboxMoveParams { from, to, id }) = params;
        self.state
            .write
            .mailbox_move(from, to, id)
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json("ok")?]))
    }

    #[tool(
        name = "message_attachment_save",
        description = "Save a message attachment to a destination path (validated to stay inside the attachment base; absolute/parent-traversal/escaping paths are rejected as invalid). WRITE: requires armed send-authority (Tier-2 remediation) and an un-tainted session; denied otherwise."
    )]
    pub async fn message_attachment_save(
        &self,
        params: Parameters<AttachmentSaveParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(AttachmentSaveParams {
            folder,
            id,
            filename,
            dest,
        }) = params;
        let saved = self
            .state
            .write
            .attachment_save(folder, id, filename, dest)
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(saved)?]))
    }

    // ----- UNGATED compose/staging (no transmission; never gated/tainting) -----
    //
    // These tools STAGE a local outbox draft; no transmission happens until a
    // later GATED connect. They validate input but never touch the guard and
    // never taint. They return the staged message id (MID). They cannot be
    // Denied — only Invalid (bad input) or Failed (op error).

    #[tool(
        name = "message_send",
        description = "Stage a composed message in the local outbox; returns the staged message id. No transmission occurs until a later gated connect. Validates recipients/subject/body; a malformed value (e.g. a CR/LF in an address) is rejected as invalid."
    )]
    pub async fn message_send(
        &self,
        params: Parameters<ComposeParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(ComposeParams {
            to,
            cc,
            subject,
            body,
        }) = params;
        let mid = self
            .state
            .compose
            .message_send(ComposeDraftDto {
                to,
                cc,
                subject,
                body,
            })
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(mid)?]))
    }

    #[tool(
        name = "send_form",
        description = "Stage a form submission in the local outbox; returns the staged message id. No transmission occurs until a later gated connect. Validates recipients and headers."
    )]
    pub async fn send_form(
        &self,
        params: Parameters<SendFormParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(SendFormParams {
            form_id,
            field_values,
            to,
            cc,
            senders_callsign,
            grid_square,
        }) = params;
        let mid = self
            .state
            .compose
            .send_form(SendFormDto {
                form_id,
                field_values,
                to,
                cc,
                senders_callsign,
                grid_square,
            })
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(mid)?]))
    }

    #[tool(
        name = "catalog_send_inquiry",
        description = "Stage a Winlink Request Center inquiry for one or more catalog item ids (the filename ids from catalog_list) in the local outbox; returns the staged message id. Use this to request ANY catalog product — propagation forecasts, METAR airport weather, satellite keplerian data, bulletins, marine forecasts, etc., not just GRIB weather. The requested products are delivered to the mailbox after the operator next connects (Arm to send). No transmission occurs here."
    )]
    pub async fn catalog_send_inquiry(
        &self,
        params: Parameters<CatalogInquiryParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(CatalogInquiryParams { item_ids }) = params;
        let mid = self
            .state
            .compose
            .catalog_send_inquiry(item_ids)
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(mid)?]))
    }

    #[tool(
        name = "grib_send_request",
        description = "Stage a GRIB weather-product request in the local outbox; returns the staged message id. No transmission occurs until a later gated connect. Validates the subject header."
    )]
    pub async fn grib_send_request(
        &self,
        params: Parameters<GribRequestParams>,
    ) -> Result<CallToolResult, ErrorData> {
        let Parameters(GribRequestParams {
            lat,
            lon,
            mode,
            subject,
        }) = params;
        let mid = self
            .state
            .compose
            .grib_send_request(GribRequestDto {
                lat,
                lon,
                mode,
                subject,
            })
            .await
            .map_err(write_err)?;
        Ok(CallToolResult::success(vec![ContentBlock::json(mid)?]))
    }
}

/// `{ "callsign": "W1AW" }` — input for `p2p_peer_password_status`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct CallsignParams {
    /// The peer station callsign to check.
    pub callsign: String,
}

/// `{ "folder": "Inbox" }` — input for `mailbox_list`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct FolderParams {
    /// The mailbox folder name to list.
    pub folder: String,
}

/// `{ "folder": "Inbox", "id": "MSG001" }` — input for `message_read`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct MessageReadParams {
    /// The folder the message lives in.
    pub folder: String,
    /// The message id to read.
    pub id: String,
}

/// `{ "query": "...", "folder": null, "limit": null }` — input for
/// `tauri_search_run`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct SearchParams {
    /// The search query string.
    pub query: String,
    /// Optional folder to scope the search to.
    #[serde(default)]
    pub folder: Option<String>,
    /// Optional maximum number of results to return.
    #[serde(default)]
    pub limit: Option<u32>,
}

/// `{ "query": "..." }` — input for `docs_search`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct QueryParams {
    /// The documentation search query string.
    pub query: String,
}

/// `{ "freq_hz": 7104000 }` — input for `rig_tune`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct RigTuneParams {
    /// The frequency in Hz to tune the rig VFO to.
    pub freq_hz: u64,
}

/// `{ "target": "KX4Z-10" }` — input for `ardop_connect`. Optional `freq_hz`
/// pre-tunes the rig for the dial; optional `qsy_candidates` supplies an ordered
/// frequency walk (operator-gated). Both omitted = legacy single dial.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct TargetParams {
    /// The target station/gateway callsign to connect to.
    pub target: String,
    /// Optional pre-audio CAT tune frequency in Hz for the single dial.
    #[serde(default)]
    pub freq_hz: Option<u64>,
    /// Optional ordered QSY candidate list; when present + non-empty it
    /// overrides `target`/`freq_hz` with a frequency walk.
    #[serde(default)]
    pub qsy_candidates: Option<Vec<QsyCandidateDto>>,
}

/// `{ "target": "KX4Z", "intent": "cms" }` — input for `ardop_b2f_exchange`.
/// `intent` selects the routing pool ([`SessionIntentDto`]:
/// `cms` / `radio-only` / `post-office` / `mesh` / `p2p`) and defaults to
/// [`SessionIntentDto::Cms`] when omitted. No frequency/QSY params: the ARDOP
/// link is tuned at connect, and the B2F runs over the already-connected link.
/// `deny_unknown_fields` (Codex tuxlink-wxwlr P2): a caller that sends `freq_hz`
/// / `qsy_candidates` here (natural, since the adjacent egress tools accept them)
/// is REJECTED rather than having those keys silently dropped — otherwise the
/// agent could believe it requested a tune while the radio transmits on the
/// existing VFO.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ExchangeParams {
    /// The target station/gateway callsign.
    pub target: String,
    /// The routing pool for the exchange; defaults to `cms` when omitted.
    #[serde(default)]
    pub intent: SessionIntentDto,
}

/// `{ "target": "KX4Z", "intent": "cms" }` — input for `vara_b2f_exchange`.
/// Like [`ExchangeParams`] but with the VARA-only `freq_hz` / `qsy_candidates`:
/// VARA's B2F connects + tunes + exchanges in a single call, so a pre-tune + QSY
/// walk are live here (unlike ARDOP, which tunes at a separate connect step).
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct VaraExchangeParams {
    /// The target station/gateway callsign.
    pub target: String,
    /// The routing pool for the exchange; defaults to `cms` when omitted.
    #[serde(default)]
    pub intent: SessionIntentDto,
    /// Optional pre-audio CAT tune frequency in Hz for the single dial.
    #[serde(default)]
    pub freq_hz: Option<u64>,
    /// Optional ordered QSY candidate list; when present + non-empty it
    /// overrides `target`/`freq_hz` with a frequency walk.
    #[serde(default)]
    pub qsy_candidates: Option<Vec<QsyCandidateDto>>,
}

/// `{ "call": "W1AW-5", "path": ["WIDE1-1"] }` — input for `packet_connect`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct PacketConnectParams {
    /// The destination station callsign.
    pub call: String,
    /// Optional ordered digipeater path; empty for a direct connection.
    #[serde(default)]
    pub path: Vec<String>,
}

/// `{ "drive_level": 80 }` — input for `config_set_ardop`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ArdopWriteParams {
    /// Transmit drive level, `0..=100`.
    pub drive_level: u8,
}

/// `{ "bandwidth_hz": 2300 }` — input for `config_set_vara`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct VaraWriteParams {
    /// VARA bandwidth in Hz; one of `500`, `2300`, `2750`.
    pub bandwidth_hz: u32,
}

/// Input for `packet_config_set`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct PacketWriteParams {
    /// Station SSID.
    pub ssid: u8,
    /// KISS TNC TCP host.
    pub tcp_host: String,
    /// KISS TNC TCP port.
    pub tcp_port: u16,
    /// TX delay in milliseconds.
    pub txdelay_ms: u32,
}

/// `{ "grid": "CN87" }` — input for `config_set_grid`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GridParams {
    /// The Maidenhead grid square to set.
    pub grid: String,
}

/// `{ "source": "gps" }` — input for `position_set_source`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct PositionSourceParams {
    /// The position source (e.g. `gps` / `manual`).
    pub source: String,
}

/// Input for `config_set_privacy`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct PrivacyParams {
    /// GPS broadcast state (e.g. `on` / `off`).
    pub gps_state: String,
    /// Position precision (e.g. a Maidenhead precision selector).
    pub precision: String,
}

/// `{ "enabled": true }` — input for `packet_set_listen`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ListenParams {
    /// Whether packet listen mode is enabled.
    pub enabled: bool,
}

/// Input for `mailbox_move`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct MailboxMoveParams {
    /// The source folder.
    pub from: String,
    /// The destination folder.
    pub to: String,
    /// The message id to move.
    pub id: String,
}

/// Input for `message_attachment_save`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct AttachmentSaveParams {
    /// The folder the message lives in.
    pub folder: String,
    /// The message id.
    pub id: String,
    /// The attachment filename within the message.
    pub filename: String,
    /// The destination path (validated to stay inside the attachment base).
    pub dest: String,
}

/// Input for `message_send`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct ComposeParams {
    /// Primary recipient addresses.
    pub to: Vec<String>,
    /// Carbon-copy recipient addresses.
    #[serde(default)]
    pub cc: Vec<String>,
    /// Message subject.
    pub subject: String,
    /// Message body.
    pub body: String,
}

/// Input for `send_form`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct SendFormParams {
    /// The catalog form id.
    pub form_id: String,
    /// The form's field name → value map.
    #[serde(default)]
    pub field_values: std::collections::BTreeMap<String, String>,
    /// Primary recipient addresses.
    pub to: Vec<String>,
    /// Carbon-copy recipient addresses.
    #[serde(default)]
    pub cc: Vec<String>,
    /// The sender's callsign.
    pub senders_callsign: String,
    /// The sender's grid square.
    pub grid_square: String,
}

/// `{ "item_ids": ["FORM-1"] }` — input for `catalog_send_inquiry`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct CatalogInquiryParams {
    /// The catalog item ids to inquire about.
    pub item_ids: Vec<String>,
}

/// Input for `grib_send_request`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct GribRequestParams {
    /// Request center latitude.
    pub lat: f64,
    /// Request center longitude.
    pub lon: f64,
    /// Request mode/product selector.
    pub mode: String,
    /// Subject line for the staged request message.
    pub subject: String,
}

/// Input for `find_stations`. All fields optional/defaultable: empty `modes` /
/// `bands` mean "no filter"; `history_hours` omitted means "no time bound".
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct StationFilterParams {
    /// Restrict to these transports (e.g. `vara-hf`, `ardop-hf`); empty = all.
    #[serde(default)]
    pub modes: Vec<crate::ports::StationModeDto>,
    /// Only gateways heard within this many hours; omitted = no bound.
    #[serde(default)]
    pub history_hours: Option<u32>,
    /// Restrict to these amateur bands (e.g. `"40m"`); empty = all bands.
    #[serde(default)]
    pub bands: Vec<String>,
}

/// Input for `predict_path`. Carries NO tx_grid — the operator's own grid is
/// injected by the impl, never agent-supplied.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct PredictRequestParams {
    /// The TARGET (receiving) station's Maidenhead grid locator.
    pub rx_grid: String,
    /// Candidate dial frequencies in kHz to predict across.
    pub frequencies_khz: Vec<f64>,
    /// The target gateway's antenna type, when known.
    #[serde(default)]
    pub gateway_antenna: Option<crate::ports::GatewayAntennaDto>,
}

/// `{ "installer_path": "/home/ham/Downloads/VARA setup.exe" }` — input for
/// `vara_install_start`.
#[derive(Debug, serde::Deserialize, schemars::JsonSchema)]
pub struct VaraInstallParams {
    /// Filesystem path to the user-downloaded VARA HF installer `.exe`.
    pub installer_path: String,
}

#[tool_handler]
impl ServerHandler for TuxlinkMcp {
    // Build `ServerInfo` (= `InitializeResult`). rmcp 2.x dropped its `Default`
    // impl in favour of `ServerInfo::new(capabilities)`, which sets the protocol
    // version to `ProtocolVersion::default()` (= `LATEST`) and `server_info` from
    // the build env; `.with_instructions(..)` attaches the operator-facing blurb.
    fn get_info(&self) -> ServerInfo {
        let capabilities = ServerCapabilities::builder()
            .enable_tools()
            .enable_prompts()
            .enable_resources()
            .build();
        ServerInfo::new(capabilities).with_instructions(
            "Tuxlink MCP server. New here? Read the resource tuxlink://agents/guide \
             first — it explains the full tool surface by tier and the arm/taint \
             rules. Read-only tools report app/backend/modem status, \
             mailbox + search content, curated config, devices, and the session log. \
             Tools that return untrusted external content (mailbox_list, message_read, \
             tauri_search_run, session_log_snapshot) taint the session, locking send \
             authority until the operator re-arms. Resources (tuxlink:// URIs) serve \
             curated operator knowledge — glossary, transport/device guides, and \
             diagnostic playbooks. Prompts walk common operator workflows.",
        )
    }

    // ----- Knowledge layer: resources + prompts (phase 3.5) -----
    //
    // These four methods are thin delegators over the context-free inherent
    // methods on `TuxlinkMcp` (the `knowledge_*` helpers below). The logic is
    // transport-free so the tier-1 tests exercise it WITHOUT constructing an
    // rmcp `RequestContext`, mirroring the `server_info_view` core-fn pattern.

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        Ok(self.knowledge_resources())
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, ErrorData> {
        self.knowledge_read(&request.uri)
    }

    async fn list_prompts(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListPromptsResult, ErrorData> {
        Ok(self.knowledge_prompts())
    }

    async fn get_prompt(
        &self,
        request: GetPromptRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> Result<GetPromptResult, ErrorData> {
        self.knowledge_get_prompt(&request.name, request.arguments)
    }
}

/// Knowledge-layer (phase 3.5) inherent methods. Context-free so they are
/// unit-testable without an rmcp transport. The `ServerHandler` resource/prompt
/// methods are thin delegators over these.
impl TuxlinkMcp {
    /// Project [`content::CATALOG`] into a [`ListResourcesResult`]. Pure.
    fn knowledge_resources(&self) -> ListResourcesResult {
        let resources = content::CATALOG
            .iter()
            .map(|r| {
                Resource::new(r.uri, r.name)
                    .with_title(r.title)
                    .with_description(r.description)
                    .with_mime_type(KNOWLEDGE_MIME)
            })
            .collect();
        ListResourcesResult::with_all_items(resources)
    }

    /// Look up a knowledge resource by URI and return its markdown body as a
    /// `text/markdown` resource content. Unknown URI → `invalid_request`.
    fn knowledge_read(&self, uri: &str) -> Result<ReadResourceResult, ErrorData> {
        let Some(resource) = content::find_by_uri(uri) else {
            return Err(ErrorData::invalid_request(
                format!("unknown resource uri: {uri}"),
                None,
            ));
        };
        // Build the TextResourceContents literal directly so the mime is the
        // correct "text/markdown" — `ResourceContents::text()` would force a
        // bare "text" mime.
        let contents = ResourceContents::TextResourceContents {
            uri: resource.uri.to_string(),
            mime_type: Some(KNOWLEDGE_MIME.to_string()),
            text: resource.markdown.to_string(),
            meta: None,
        };
        Ok(ReadResourceResult::new(vec![contents]))
    }

    /// The three knowledge-layer prompts. Pure.
    fn knowledge_prompts(&self) -> ListPromptsResult {
        let prompts = vec![
            Prompt::new(
                "diagnose_my_connection",
                Some(
                    "Diagnose why a connection or transport is not working, read-only. \
                     Optional `transport` (ardop/vara/packet/telnet) focuses the walk.",
                ),
                Some(vec![PromptArgument::new("transport")
                    .with_title("Transport")
                    .with_description(
                        "Optional transport to focus on: ardop, vara, packet, or telnet.",
                    )
                    .with_required(false)]),
            ),
            Prompt::new(
                "help_me_set_up",
                Some(
                    "Walk through setting up a device or PTT method. Requires `device` \
                     (e.g. uv-pro, digirig, ptt).",
                ),
                Some(vec![PromptArgument::new("device")
                    .with_title("Device")
                    .with_description(
                        "The device or method to set up (e.g. uv-pro, digirig, ptt).",
                    )
                    .with_required(true)]),
            ),
            Prompt::new(
                "compose_an_ics_213",
                Some(
                    "Help compose an ICS-213 general message and stage it (no transmission). \
                     Optional `to` and `subject` pre-fill fields.",
                ),
                Some(vec![
                    PromptArgument::new("to")
                        .with_title("To")
                        .with_description("Optional recipient address(es).")
                        .with_required(false),
                    PromptArgument::new("subject")
                        .with_title("Subject")
                        .with_description("Optional message subject.")
                        .with_required(false),
                ]),
            ),
        ];
        ListPromptsResult::with_all_items(prompts)
    }

    /// Render the named prompt with the supplied arguments. Unknown name →
    /// `invalid_request`; a missing required arg (`help_me_set_up.device`) →
    /// `invalid_request`. Pure.
    fn knowledge_get_prompt(
        &self,
        name: &str,
        arguments: Option<rmcp::model::JsonObject>,
    ) -> Result<GetPromptResult, ErrorData> {
        let args = arguments.unwrap_or_default();
        let arg = |key: &str| -> Option<String> {
            args.get(key)
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
        };

        match name {
            "diagnose_my_connection" => {
                let transport = arg("transport");
                let (transport_line, playbook_line) = match transport.as_deref() {
                    Some(t) if t.eq_ignore_ascii_case("ardop") => (
                        "The operator is using the ARDOP transport.".to_string(),
                        "Also read the resource tuxlink://playbook/ardop-wont-connect and \
                         tuxlink://guide/ardop."
                            .to_string(),
                    ),
                    Some(t) if t.eq_ignore_ascii_case("vara") => (
                        "The operator is using the VARA HF transport.".to_string(),
                        "Also read the resource tuxlink://guide/vara.".to_string(),
                    ),
                    Some(t) if t.eq_ignore_ascii_case("packet") => (
                        "The operator is using the packet (AX.25) transport.".to_string(),
                        "Also read the resource tuxlink://guide/packet.".to_string(),
                    ),
                    Some(t) => (
                        format!("The operator is using the {t} transport."),
                        "Also read the resource tuxlink://guide/picking-a-transport.".to_string(),
                    ),
                    None => (
                        "The transport was not specified; determine it from the diagnostics."
                            .to_string(),
                        "Read the resource tuxlink://guide/picking-a-transport to identify the \
                         transport in use."
                            .to_string(),
                    ),
                };
                let text = format!(
                    "Diagnose why the operator's connection is not working. {transport_line}\n\n\
                     1. Read the resource tuxlink://playbook/connection-troubleshooting. \
                     {playbook_line}\n\
                     2. Call the read-only diagnostic tools to gather current state: \
                     backend_status, modem_get_status, config_read, and \
                     session_log_snapshot.\n\
                     3. Correlate the diagnostics against the playbook's failure points and \
                     explain plainly, in operator language, what is wrong and the next step.\n\n\
                     DO NOT transmit, connect, or change any configuration. This is a \
                     read-only diagnosis; staging or transmission is the operator's call."
                );
                Ok(GetPromptResult::new(vec![PromptMessage::new_text(Role::User, text)])
                    .with_description("Read-only connection diagnosis walk."))
            }
            "help_me_set_up" => {
                let Some(device) = arg("device") else {
                    return Err(ErrorData::invalid_request(
                        "help_me_set_up requires a `device` argument".to_string(),
                        None,
                    ));
                };
                let resource_line = if device.eq_ignore_ascii_case("uv-pro")
                    || device.eq_ignore_ascii_case("uvpro")
                {
                    "Read the resource tuxlink://device/uv-pro."
                } else if device.eq_ignore_ascii_case("ptt") {
                    "Read the resource tuxlink://guide/ptt."
                } else {
                    "Read the resource tuxlink://guide/ptt and tuxlink://device/uv-pro for the \
                     closest matching guidance."
                };
                let text = format!(
                    "Help the operator set up: {device}.\n\n\
                     1. {resource_line}\n\
                     2. Read the current configuration with config_read (and \
                     config_get_ardop / config_get_vara / packet_config_get as relevant) and \
                     enumerate hardware with packet_list_serial_devices, \
                     packet_list_bluetooth_devices, and ardop_list_audio_devices.\n\
                     3. Walk the operator through the configuration step by step, in plain \
                     language, matching the guide to what the diagnostics show.\n\n\
                     Configuration writes require the operator's armed send authority; \
                     propose the values and let the operator apply them. Do not transmit."
                );
                Ok(GetPromptResult::new(vec![PromptMessage::new_text(Role::User, text)])
                    .with_description(format!("Setup walk for {device}.")))
            }
            "compose_an_ics_213" => {
                let to = arg("to");
                let subject = arg("subject");
                let mut prefill = String::new();
                if let Some(to) = to {
                    prefill.push_str(&format!("\nRecipient (To): {to}"));
                }
                if let Some(subject) = subject {
                    prefill.push_str(&format!("\nSubject: {subject}"));
                }
                let text = format!(
                    "Help the operator compose an ICS-213 General Message.\n\n\
                     1. Read the resource tuxlink://guide/emcomm-ics for the ICS context and \
                     form usage.\n\
                     2. Collect the ICS-213 fields with the operator: To, From, Subject, \
                     Date, Time, Message, Approved By (name + position/title), and the \
                     reply section if a response is expected.\n\
                     3. Stage the message as a local outbox draft using send_form (or \
                     message_send for a plain message). Return the staged message id.\
                     {prefill}\n\n\
                     Staging only — no transmission occurs. The message stays in the local \
                     outbox until the operator arms send authority and runs a gated connect."
                );
                Ok(GetPromptResult::new(vec![PromptMessage::new_text(Role::User, text)])
                    .with_description("ICS-213 compose-and-stage walk."))
            }
            other => Err(ErrorData::invalid_request(
                format!("unknown prompt: {other}"),
                None,
            )),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicBool, Ordering};

    use crate::ports::{MessageMetaDto, ParsedMessageDto};
    use crate::test_support::{
        state_with_all_probes, state_with_egress_probes, state_with_guard, SEED_GW_CALLSIGN,
        SEED_GW_GRID, SEED_MSG_FROM, SEED_MSG_ID, SEED_MSG_SUBJECT, SEED_TX_GRID,
    };
    use tuxlink_security::EgressGuard;

    fn handler() -> TuxlinkMcp {
        TuxlinkMcp::new(Arc::new(state_with_guard(EgressGuard::new())))
    }

    /// Deterministic clock so an armed grant is un-expired within the test.
    fn fixed_1000() -> u64 {
        1000
    }

    /// Build a handler plus the egress `op_ran` + `aborted` probe flags, all
    /// sharing one guard (on a fixed clock so arm() is live).
    fn handler_with_probes() -> (TuxlinkMcp, Arc<AtomicBool>, Arc<AtomicBool>) {
        let (state, op_ran, aborted) =
            state_with_egress_probes(EgressGuard::with_clock(fixed_1000));
        (TuxlinkMcp::new(Arc::new(state)), op_ran, aborted)
    }

    /// Handler plus `(op_ran, staged)` for the write + compose tier-1 tests.
    /// `op_ran` is shared by the gated write mock; `staged` is flipped by the
    /// ungated compose mock.
    fn handler_with_write_probes() -> (TuxlinkMcp, Arc<AtomicBool>, Arc<AtomicBool>) {
        let (state, op_ran, _aborted, staged) =
            state_with_all_probes(EgressGuard::with_clock(fixed_1000));
        (TuxlinkMcp::new(Arc::new(state)), op_ran, staged)
    }

    /// Extract + deserialize the JSON the tool packed into its first text
    /// content. `ContentBlock::json` serializes to a text content carrying the JSON.
    fn json_of<T: serde::de::DeserializeOwned>(result: &CallToolResult) -> T {
        let text = result.content[0]
            .as_text()
            .expect("tool result must be a JSON text content")
            .text
            .clone();
        serde_json::from_str(&text).expect("tool JSON must deserialize back into the DTO")
    }

    // --- TAINT tools flip the guard ---

    #[tokio::test]
    async fn mailbox_list_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.mailbox_list(Parameters(FolderParams {
            folder: "Inbox".into(),
        }))
        .await
        .unwrap();
        assert!(h.state.guard.is_tainted(), "mailbox_list must taint");
    }

    #[tokio::test]
    async fn message_read_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.message_read(Parameters(MessageReadParams {
            folder: "Inbox".into(),
            id: SEED_MSG_ID.into(),
        }))
        .await
        .unwrap();
        assert!(h.state.guard.is_tainted(), "message_read must taint");
    }

    #[tokio::test]
    async fn tauri_search_run_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.tauri_search_run(Parameters(SearchParams {
            query: "ares".into(),
            folder: None,
            limit: None,
        }))
        .await
        .unwrap();
        assert!(h.state.guard.is_tainted(), "tauri_search_run must taint");
    }

    #[tokio::test]
    async fn session_log_snapshot_taints() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        h.session_log_snapshot().await.unwrap();
        assert!(
            h.state.guard.is_tainted(),
            "session_log_snapshot must taint"
        );
    }

    // --- NON-taint tools leave a fresh guard clean ---

    #[tokio::test]
    async fn non_taint_tools_do_not_taint() {
        let h = handler();
        h.backend_status().await.unwrap();
        h.config_read().await.unwrap();
        h.platform_info().await.unwrap();
        h.docs_search(Parameters(QueryParams {
            query: "start".into(),
        }))
        .await
        .unwrap();
        h.user_folders_list().await.unwrap();
        h.catalog_list().await.unwrap();
        h.packet_list_serial_devices().await.unwrap();
        h.p2p_peer_password_status(Parameters(CallsignParams {
            callsign: "W1AW".into(),
        }))
        .await
        .unwrap();
        assert!(
            !h.state.guard.is_tainted(),
            "read-only status/config/docs/devices tools must NOT taint a fresh guard"
        );
    }

    // --- DTO round-trips through the tool result ---

    #[tokio::test]
    async fn message_read_round_trips_dto() {
        let h = handler();
        let result = h
            .message_read(Parameters(MessageReadParams {
                folder: "Inbox".into(),
                id: SEED_MSG_ID.into(),
            }))
            .await
            .unwrap();
        let dto: ParsedMessageDto = json_of(&result);
        assert_eq!(dto.id, SEED_MSG_ID);
        assert_eq!(dto.from, SEED_MSG_FROM);
        assert_eq!(dto.subject, SEED_MSG_SUBJECT);
    }

    #[tokio::test]
    async fn mailbox_list_round_trips_dto() {
        let h = handler();
        let result = h
            .mailbox_list(Parameters(FolderParams {
                folder: "Inbox".into(),
            }))
            .await
            .unwrap();
        let items: Vec<MessageMetaDto> = json_of(&result);
        assert_eq!(items.len(), 1);
        assert_eq!(items[0].from, SEED_MSG_FROM);
        assert_eq!(items[0].subject, SEED_MSG_SUBJECT);
    }

    #[tokio::test]
    async fn config_read_round_trips_grid() {
        let h = handler();
        let result = h.config_read().await.unwrap();
        let dto: crate::ports::ConfigViewDto = json_of(&result);
        assert_eq!(dto.grid, "CN87", "grid must be the 4-char fixture value");
    }

    // --- rig CAT-control read tools (no taint, no gate) ---

    #[tokio::test]
    async fn rig_status_returns_dto_and_does_not_taint() {
        use crate::ports::RigStatusDto;
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        let result = h.rig_status().await.unwrap();
        let dto: RigStatusDto = json_of(&result);
        assert!(dto.configured, "the mock reports rig control configured");
        assert_eq!(dto.vfo_hz, Some(7_104_000));
        assert_eq!(dto.mode.as_deref(), Some("PKTUSB"));
        assert_eq!(dto.ptt, Some(false));
        assert!(
            !h.state.guard.is_tainted(),
            "rig_status is a read-only CAT probe and must NOT taint the session"
        );
    }

    #[tokio::test]
    async fn config_get_rig_returns_dto_and_does_not_taint() {
        use crate::ports::RigConfigDto;
        let h = handler();
        let result = h.config_get_rig().await.unwrap();
        let dto: RigConfigDto = json_of(&result);
        assert_eq!(dto.rig_hamlib_model, Some(1035));
        assert_eq!(dto.rigctld_port, 4534);
        assert_eq!(dto.cat_serial_path.as_deref(), Some("/dev/ttyUSB0"));
        assert!(
            !h.state.guard.is_tainted(),
            "config_get_rig must NOT taint the session"
        );
    }

    // --- Station intelligence: inert reads (no taint, no gate) ---

    #[tokio::test]
    async fn find_stations_returns_seeded_gateway_and_does_not_taint() {
        use crate::ports::StationListDto;
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        let result = h
            .find_stations(Parameters(StationFilterParams {
                modes: vec![],
                history_hours: None,
                bands: vec![],
            }))
            .await
            .unwrap();
        let dto: StationListDto = json_of(&result);
        assert_eq!(dto.gateways.len(), 1, "the mock seeds exactly one gateway");
        assert_eq!(dto.gateways[0].callsign, SEED_GW_CALLSIGN);
        assert_eq!(dto.gateways[0].grid.as_deref(), Some(SEED_GW_GRID));
        assert_eq!(
            dto.fetched_at_ms,
            Some(0),
            "the seeded fetch carries a freshness stamp the agent reasons from"
        );
        assert!(
            !h.state.guard.is_tainted(),
            "find_stations must NOT taint the session (public directory data)"
        );
    }

    #[tokio::test]
    async fn predict_path_returns_24h_vectors_and_4char_tx_grid_and_does_not_taint() {
        use crate::ports::PathPredictionDto;
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        let result = h
            .predict_path(Parameters(PredictRequestParams {
                rx_grid: "FN31".into(),
                frequencies_khz: vec![7104.0],
                gateway_antenna: None,
            }))
            .await
            .unwrap();
        let dto: PathPredictionDto = json_of(&result);
        assert_eq!(
            dto.tx_grid, SEED_TX_GRID,
            "tx_grid is the impl-injected provenance grid"
        );
        assert_eq!(dto.tx_grid.len(), 4, "tx_grid must be the 4-char provenance grid");
        assert_eq!(dto.channels.len(), 1, "the mock returns one channel");
        let ch = &dto.channels[0];
        assert_eq!(ch.rel_by_hour.len(), 24, "rel vector is 24-long (UTC 0..23)");
        assert_eq!(ch.snr_by_hour.len(), 24, "snr vector is 24-long");
        assert_eq!(ch.mufday_by_hour.len(), 24, "mufday vector is 24-long");
        assert!(
            !h.state.guard.is_tainted(),
            "predict_path must NOT taint the session (offline computation)"
        );
    }

    #[tokio::test]
    async fn solar_conditions_returns_snapshot_and_does_not_taint() {
        use crate::ports::SolarSnapshotDto;
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        let result = h.solar_conditions().await.unwrap();
        let dto: SolarSnapshotDto = json_of(&result);
        assert_eq!(dto.sfi, Some(140.0));
        assert_eq!(dto.a_index, Some(7.0));
        assert_eq!(dto.k_index, Some(2.0));
        assert_eq!(dto.ssn, 70.0);
        assert_eq!(dto.source, "bundled");
        assert!(
            !h.state.guard.is_tainted(),
            "solar_conditions must NOT taint the session (public data)"
        );
    }

    // --- Provisioning: VARA-under-WINE (reads + ungated non-transmit install) ---

    #[tokio::test]
    async fn vara_engine_available_returns_bool_and_does_not_taint() {
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        let result = h.vara_engine_available().await.unwrap();
        let available: bool = json_of(&result);
        assert!(available, "the mock reports the setup engine bundled");
        assert!(
            !h.state.guard.is_tainted(),
            "vara_engine_available is a read and must NOT taint"
        );
    }

    #[tokio::test]
    async fn vara_install_status_returns_dto_and_does_not_taint() {
        use crate::ports::VaraInstallStatusDto;
        let h = handler();
        assert!(!h.state.guard.is_tainted());
        let result = h.vara_install_status().await.unwrap();
        let dto: VaraInstallStatusDto = json_of(&result);
        assert!(!dto.ready, "the mock reports VARA not yet provisioned");
        assert_eq!(dto.checkpoints.len(), 1, "the mock seeds one checkpoint");
        assert_eq!(dto.checkpoints[0].id.as_deref(), Some("deps"));
        assert!(
            !h.state.guard.is_tainted(),
            "vara_install_status is an offline read and must NOT taint"
        );
    }

    #[tokio::test]
    async fn vara_install_start_runs_ungated_on_disarmed_guard() {
        use crate::ports::VaraInstallSummaryDto;
        // Provisioning is NON-TRANSMIT and ungated: unlike the egress/write tier,
        // the install must run and succeed on a FRESH, DISARMED guard. Because
        // MockProvision flips the SHARED `op_ran` (which only a gated egress/write
        // op would otherwise touch), and nothing arms the guard here, `op_ran`
        // flipping proves the ungated install actually executed.
        let (h, op_ran, _staged) = handler_with_write_probes();
        assert!(!h.state.guard.is_tainted());
        assert!(!op_ran.load(Ordering::SeqCst));
        let result = h
            .vara_install_start(Parameters(VaraInstallParams {
                installer_path: "/home/ham/Downloads/VARA setup.exe".into(),
            }))
            .await
            .expect("provisioning is ungated; must succeed on a disarmed guard");
        let dto: VaraInstallSummaryDto = json_of(&result);
        assert!(dto.ok, "the mock reports a green install");
        assert_eq!(dto.vara_version.as_deref(), Some("VARA HF"));
        assert!(
            op_ran.load(Ordering::SeqCst),
            "the underlying install op must have run without any arm (ungated)"
        );
        assert!(
            !h.state.guard.is_tainted(),
            "provisioning must NOT taint the session"
        );
    }

    // --- STEP 6: egress gate + injection-containment via the real tools ---

    #[tokio::test]
    async fn gated_egress_on_unarmed_guard_denies_and_op_never_runs() {
        let (h, op_ran, _aborted) = handler_with_probes();
        // Fresh guard is unarmed → the gated egress tool must be denied.
        let err = h.cms_connect().await.expect_err("unarmed must deny");
        assert!(
            err.message.contains("not authorized"),
            "denial message must name the missing authorization, got: {}",
            err.message
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "the underlying egress op must NEVER run when denied"
        );
    }

    #[tokio::test]
    async fn gated_egress_after_arm_is_allowed_and_op_runs() {
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.arm(30); // arm send authority (deadline 1030, now 1000)
        h.cms_connect().await.expect("armed + untainted must allow");
        assert!(
            op_ran.load(Ordering::SeqCst),
            "the underlying egress op must run once authorized"
        );
    }

    #[tokio::test]
    async fn gated_egress_denied_when_tainted_even_if_armed() {
        // Simulate a prior malicious read tainting the session, then arming.
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.taint(); // a prior message_read/search tainted the session
        h.state.guard.arm(30); // arming does NOT clear taint
        let err = h
            .ardop_connect(Parameters(TargetParams {
                target: "KX4Z-10".into(),
                freq_hz: None,
                qsy_candidates: None,
            }))
            .await
            .expect_err("tainted must deny even when armed");
        assert!(err.message.contains("not authorized"));
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "a tainted session must not transmit even while armed"
        );
    }

    #[tokio::test]
    async fn gated_egress_allowed_after_clear_taint_and_fresh_arm() {
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.taint();
        h.state.guard.clear_taint(); // explicit session reset
        h.state.guard.arm(30);
        h.vara_b2f_exchange(Parameters(VaraExchangeParams {
            target: "KX4Z".into(),
            intent: SessionIntentDto::Cms,
            freq_hz: None,
            qsy_candidates: None,
        }))
        .await
        .expect("fresh arm after clear_taint must allow");
        assert!(op_ran.load(Ordering::SeqCst), "op must run after a clean re-arm");
    }

    #[tokio::test]
    async fn rig_tune_denied_when_unarmed_and_op_never_runs() {
        // rig_tune rides the SAME egress gate as transmit: an unarmed session is
        // denied and the underlying CAT tune never runs.
        let (h, op_ran, _aborted) = handler_with_probes();
        let err = h
            .rig_tune(Parameters(RigTuneParams {
                freq_hz: 7_104_000,
            }))
            .await
            .expect_err("unarmed rig_tune must deny");
        assert!(
            err.message.contains("not authorized"),
            "denial must name the missing authorization, got: {}",
            err.message
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "the underlying rig tune must NEVER run when denied"
        );
    }

    #[tokio::test]
    async fn rig_tune_allowed_after_arm_and_op_runs() {
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.arm(30);
        h.rig_tune(Parameters(RigTuneParams {
            freq_hz: 7_104_000,
        }))
        .await
        .expect("armed + untainted rig_tune must allow");
        assert!(
            op_ran.load(Ordering::SeqCst),
            "the underlying rig tune must run once authorized"
        );
    }

    #[tokio::test]
    async fn rig_tune_denied_when_tainted_even_if_armed() {
        let (h, op_ran, _aborted) = handler_with_probes();
        h.state.guard.taint();
        h.state.guard.arm(30); // arming does NOT clear taint
        let err = h
            .rig_tune(Parameters(RigTuneParams {
                freq_hz: 7_104_000,
            }))
            .await
            .expect_err("tainted rig_tune must deny even when armed");
        assert!(err.message.contains("not authorized"));
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "a tainted session must not tune even while armed"
        );
    }

    #[test]
    fn target_params_deserialize_with_freq_and_qsy_candidates() {
        // The parity params parse: a connect call carrying freq_hz +
        // qsy_candidates (snake_case wire form) deserializes into TargetParams.
        let json = r#"{
            "target": "KX4Z-10",
            "freq_hz": 7104000,
            "qsy_candidates": [
                {"target": "KX4Z-10", "freq_hz": 7104000},
                {"target": "W1AW-10", "freq_hz": null}
            ]
        }"#;
        let p: TargetParams = serde_json::from_str(json).expect("parity params must parse");
        assert_eq!(p.target, "KX4Z-10");
        assert_eq!(p.freq_hz, Some(7_104_000));
        let cands = p.qsy_candidates.expect("candidates present");
        assert_eq!(cands.len(), 2);
        assert_eq!(cands[0].freq_hz, Some(7_104_000));
        assert_eq!(cands[1].freq_hz, None);
    }

    #[test]
    fn target_params_deserialize_legacy_target_only() {
        // The legacy `{ target }` shape still parses (both new fields default to
        // None), so a pre-rig-control caller is unaffected.
        let p: TargetParams =
            serde_json::from_str(r#"{ "target": "KX4Z-10" }"#).expect("legacy shape must parse");
        assert_eq!(p.target, "KX4Z-10");
        assert_eq!(p.freq_hz, None);
        assert!(p.qsy_candidates.is_none());
    }

    #[test]
    fn vara_exchange_params_deserialize_with_freq_and_qsy_candidates() {
        // VARA b2f carries freq/qsy (it connects + tunes + exchanges in one
        // call); ARDOP b2f does not (it tunes at the separate connect step).
        let json = r#"{
            "target": "KX4Z",
            "intent": "p2p",
            "freq_hz": 14105000,
            "qsy_candidates": [{"target": "KX4Z", "freq_hz": 14105000}]
        }"#;
        let p: VaraExchangeParams = serde_json::from_str(json).expect("parity params must parse");
        assert_eq!(p.target, "KX4Z");
        assert_eq!(p.intent, SessionIntentDto::P2p);
        assert_eq!(p.freq_hz, Some(14_105_000));
        assert_eq!(p.qsy_candidates.map(|c| c.len()), Some(1));
    }

    #[test]
    fn ardop_exchange_params_have_no_freq_or_qsy_fields() {
        // ExchangeParams (ARDOP b2f) is target+intent only; freq/qsy keys in the
        // JSON are ignored (serde default deny_unknown is off), and the struct
        // exposes no such fields. The ARDOP link is tuned at connect.
        let p: ExchangeParams = serde_json::from_str(r#"{ "target": "KX4Z", "intent": "cms" }"#)
            .expect("ardop exchange params must parse");
        assert_eq!(p.target, "KX4Z");
        assert_eq!(p.intent, SessionIntentDto::Cms);
    }

    #[tokio::test]
    async fn abort_tool_succeeds_regardless_of_guard_state() {
        // Unarmed + tainted: the abort tool must STILL succeed (never gated).
        let (h, _op_ran, aborted) = handler_with_probes();
        h.state.guard.taint(); // hostile state
        h.cms_abort().await.expect("abort is never gated");
        assert!(
            aborted.load(Ordering::SeqCst),
            "the underlying abort must fire regardless of guard state"
        );
    }

    #[tokio::test]
    async fn all_abort_tools_succeed_when_tainted_and_unarmed() {
        let (h, _op_ran, aborted) = handler_with_probes();
        h.state.guard.taint();
        h.cms_abort().await.unwrap();
        h.modem_ardop_disconnect().await.unwrap();
        h.vara_stop_session().await.unwrap();
        assert!(aborted.load(Ordering::SeqCst));
    }

    // --- STEP 5: gated WRITE tier (validate-before-gate) via the real tools ---

    #[tokio::test]
    async fn write_denied_when_unarmed_and_op_never_runs() {
        let (h, op_ran, _staged) = handler_with_write_probes();
        let err = h
            .config_set_ardop(Parameters(ArdopWriteParams { drive_level: 80 }))
            .await
            .expect_err("unarmed write must deny");
        assert!(
            err.message.contains("not authorized"),
            "denial must name the missing authorization, got: {}",
            err.message
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "the underlying write op must NOT run when denied"
        );
    }

    #[tokio::test]
    async fn write_denied_when_tainted_even_if_armed() {
        let (h, op_ran, _staged) = handler_with_write_probes();
        h.state.guard.taint();
        h.state.guard.arm(30); // arming does NOT clear taint
        let err = h
            .config_set_ardop(Parameters(ArdopWriteParams { drive_level: 80 }))
            .await
            .expect_err("tainted write must deny even when armed");
        assert!(err.message.contains("not authorized"));
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "a tainted session must not write even while armed"
        );
    }

    #[tokio::test]
    async fn write_allowed_when_armed_and_untainted_and_op_runs() {
        let (h, op_ran, _staged) = handler_with_write_probes();
        h.state.guard.arm(30);
        h.config_set_ardop(Parameters(ArdopWriteParams { drive_level: 80 }))
            .await
            .expect("armed + untainted write must allow");
        assert!(
            op_ran.load(Ordering::SeqCst),
            "the underlying write op must run once authorized"
        );
    }

    #[tokio::test]
    async fn write_invalid_input_is_rejected_even_when_unarmed() {
        // validate-before-gate: an out-of-range drive level is `invalid`, NOT a
        // `not authorized` denial, even though the session is unarmed — proving
        // validation runs BEFORE the gate and does not consume the arm grant.
        let (h, op_ran, _staged) = handler_with_write_probes();
        let err = h
            .config_set_ardop(Parameters(ArdopWriteParams { drive_level: 200 }))
            .await
            .expect_err("out-of-range drive level must be rejected");
        assert!(
            !err.message.contains("not authorized"),
            "an invalid input must NOT be reported as an authorization denial, got: {}",
            err.message
        );
        assert!(
            err.message.contains("drive_level"),
            "the invalid-input message must name the offending field, got: {}",
            err.message
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "an invalid input must never reach the gated op"
        );
    }

    #[tokio::test]
    async fn attachment_save_traversal_dest_is_invalid() {
        // Even unarmed, a parent-traversal dest is rejected as invalid (not a
        // denial) by the validate-before-gate check.
        let (h, op_ran, _staged) = handler_with_write_probes();
        let err = h
            .message_attachment_save(Parameters(AttachmentSaveParams {
                folder: "Inbox".into(),
                id: SEED_MSG_ID.into(),
                filename: "roster.txt".into(),
                dest: "../../etc/x".into(),
            }))
            .await
            .expect_err("a traversal dest must be rejected");
        assert!(
            !err.message.contains("not authorized"),
            "a traversal dest must be invalid, not an authorization denial, got: {}",
            err.message
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "an invalid dest must never reach the gated save op"
        );
    }

    // --- STEP 5: UNGATED compose tier (no arm, no taint, no op flag) ---

    #[tokio::test]
    async fn compose_message_send_allowed_without_arm_and_does_not_gate_or_taint() {
        // Compose is ungated: it succeeds on a fresh (unarmed, untainted) guard,
        // returns a staged MID, does NOT flip the egress op flag, and does NOT
        // taint the session.
        let (h, op_ran, staged) = handler_with_write_probes();
        assert!(!h.state.guard.is_tainted());
        let result = h
            .message_send(Parameters(ComposeParams {
                to: vec!["W1AW@winlink.org".into()],
                cc: vec![],
                subject: "ARES net".into(),
                body: "Check in.".into(),
            }))
            .await
            .expect("compose must succeed without an arm (ungated)");
        let mid: String = json_of(&result);
        assert!(!mid.is_empty(), "compose must return a staged MID");
        assert!(
            staged.load(Ordering::SeqCst),
            "compose must stage the draft locally"
        );
        assert!(
            !op_ran.load(Ordering::SeqCst),
            "compose must NOT fire the egress op flag (no transmission staged)"
        );
        assert!(
            !h.state.guard.is_tainted(),
            "compose must NOT taint the session"
        );
    }

    #[tokio::test]
    async fn compose_message_send_with_header_injection_address_is_invalid() {
        let (h, _op_ran, staged) = handler_with_write_probes();
        let err = h
            .message_send(Parameters(ComposeParams {
                to: vec!["a@b.com\r\nBcc: evil@x.com".into()],
                cc: vec![],
                subject: "hi".into(),
                body: "body".into(),
            }))
            .await
            .expect_err("a CR/LF address must be rejected");
        assert!(
            !err.message.contains("not authorized"),
            "a malformed address must be invalid, not a denial, got: {}",
            err.message
        );
        assert!(
            !staged.load(Ordering::SeqCst),
            "an invalid compose must NOT stage a draft"
        );
    }

    // --- STEP 3.5: knowledge layer (resources + prompts) ---

    #[test]
    fn list_resources_returns_full_catalog() {
        let h = handler();
        let result = h.knowledge_resources();
        assert_eq!(
            result.resources.len(),
            content::CATALOG.len(),
            "list_resources must project the entire catalog"
        );
        let uris: Vec<&str> = result.resources.iter().map(|r| r.uri.as_str()).collect();
        // The new authored playbooks must be present.
        assert!(uris.contains(&"tuxlink://playbook/ardop-wont-connect"));
        assert!(uris.contains(&"tuxlink://playbook/cms-z-password-lag"));
        assert!(uris.contains(&"tuxlink://device/uv-pro"));
        assert!(uris.contains(&"tuxlink://reference/modem-capability-matrix"));
        // The VARA-under-WINE provisioning playbook (tuxlink-w7212) must be present.
        assert!(uris.contains(&"tuxlink://playbook/vara-wine-setup"));
        // A curated user-guide resource must be present too.
        assert!(uris.contains(&"tuxlink://guide/ardop"));
    }

    #[test]
    fn list_resources_advertises_markdown_mime() {
        let h = handler();
        let result = h.knowledge_resources();
        for r in &result.resources {
            assert_eq!(
                r.mime_type.as_deref(),
                Some("text/markdown"),
                "every resource must advertise the text/markdown mime"
            );
        }
    }

    #[test]
    fn read_resource_known_uri_returns_markdown_text() {
        let h = handler();
        let result = h
            .knowledge_read("tuxlink://playbook/ardop-wont-connect")
            .expect("a known uri must read successfully");
        assert_eq!(result.contents.len(), 1);
        match &result.contents[0] {
            ResourceContents::TextResourceContents {
                uri,
                mime_type,
                text,
                ..
            } => {
                assert_eq!(uri, "tuxlink://playbook/ardop-wont-connect");
                assert_eq!(
                    mime_type.as_deref(),
                    Some("text/markdown"),
                    "the content mime must be text/markdown, not a bare \"text\""
                );
                assert!(!text.is_empty(), "the markdown body must be non-empty");
                assert!(
                    text.contains("ARDOP"),
                    "the body must be the ARDOP playbook content"
                );
            }
            other => panic!("expected TextResourceContents, got {other:?}"),
        }
    }

    #[test]
    fn read_resource_unknown_uri_is_invalid_request() {
        let h = handler();
        let err = h
            .knowledge_read("tuxlink://does-not-exist")
            .expect_err("an unknown uri must error");
        assert!(
            err.message.contains("unknown resource uri"),
            "the error must name the unknown-resource condition, got: {}",
            err.message
        );
    }

    #[test]
    fn list_prompts_returns_three_prompts_with_args() {
        let h = handler();
        let result = h.knowledge_prompts();
        assert_eq!(result.prompts.len(), 3, "exactly three prompts");
        let by_name = |name: &str| result.prompts.iter().find(|p| p.name == name);

        let diagnose = by_name("diagnose_my_connection").expect("diagnose prompt present");
        let diagnose_args = diagnose.arguments.as_ref().expect("diagnose has args");
        assert_eq!(diagnose_args[0].name, "transport");
        assert_eq!(diagnose_args[0].required, Some(false));

        let setup = by_name("help_me_set_up").expect("setup prompt present");
        let setup_args = setup.arguments.as_ref().expect("setup has args");
        assert_eq!(setup_args[0].name, "device");
        assert_eq!(
            setup_args[0].required,
            Some(true),
            "device is the required setup arg"
        );

        let ics = by_name("compose_an_ics_213").expect("ics prompt present");
        let ics_args = ics.arguments.as_ref().expect("ics has args");
        let ics_names: Vec<&str> = ics_args.iter().map(|a| a.name.as_str()).collect();
        assert!(ics_names.contains(&"to"));
        assert!(ics_names.contains(&"subject"));
    }

    #[test]
    fn get_prompt_diagnose_ardop_references_the_playbooks() {
        let h = handler();
        let mut args = rmcp::model::JsonObject::new();
        args.insert("transport".to_string(), serde_json::json!("ardop"));
        let result = h
            .knowledge_get_prompt("diagnose_my_connection", Some(args))
            .expect("diagnose prompt renders");
        assert_eq!(result.messages.len(), 1);
        let msg = &result.messages[0];
        assert_eq!(msg.role, Role::User);
        let text = match &msg.content {
            ContentBlock::Text(tc) => tc.text.clone(),
            other => panic!("expected a Text prompt message, got {other:?}"),
        };
        assert!(
            text.contains("ardop-wont-connect"),
            "the ardop diagnosis must cite the ARDOP playbook"
        );
        assert!(
            text.contains("connection-troubleshooting"),
            "the diagnosis must cite the connection-troubleshooting playbook"
        );
        assert!(
            text.contains("DO NOT transmit"),
            "the diagnosis must instruct read-only (no transmit)"
        );
    }

    #[test]
    fn get_prompt_setup_requires_device() {
        let h = handler();
        let err = h
            .knowledge_get_prompt("help_me_set_up", None)
            .expect_err("missing required device must error");
        assert!(err.message.contains("device"), "error must name the missing arg");
    }

    #[test]
    fn get_prompt_unknown_name_is_invalid_request() {
        let h = handler();
        let err = h
            .knowledge_get_prompt("no_such_prompt", None)
            .expect_err("an unknown prompt name must error");
        assert!(err.message.contains("unknown prompt"));
    }

    #[test]
    fn agents_guide_resource_is_present_and_readable() {
        let h = handler();
        // The catalog advertises the agent onboarding guide.
        let listed = h
            .knowledge_resources()
            .resources
            .iter()
            .any(|r| r.uri == "tuxlink://agents/guide");
        assert!(listed, "the catalog must advertise the agent guide");
        // It reads back as non-empty markdown.
        let result = h
            .knowledge_read("tuxlink://agents/guide")
            .expect("the agent guide must read successfully");
        match &result.contents[0] {
            ResourceContents::TextResourceContents { text, .. } => {
                assert!(!text.is_empty(), "the agent guide body must be non-empty");
            }
            other => panic!("expected TextResourceContents, got {other:?}"),
        }
        // get_info points new callers at the guide.
        let info = h.get_info();
        assert!(
            info.instructions
                .as_deref()
                .is_some_and(|s| s.contains("tuxlink://agents/guide")),
            "get_info instructions must point at the agent guide"
        );
    }

    #[test]
    fn get_info_advertises_resources_and_prompts() {
        let h = handler();
        let info = h.get_info();
        assert!(
            info.capabilities.resources.is_some(),
            "get_info must advertise resources capability"
        );
        assert!(
            info.capabilities.prompts.is_some(),
            "get_info must advertise prompts capability"
        );
        assert!(
            info.capabilities.tools.is_some(),
            "tools capability must remain advertised"
        );
    }
}
